
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 18 01:22:16 CST 2025
//----------------------------------------------------

package act2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIFERENCIA = 35;
  public static final int PARENTESIS_CIERRE = 48;
  public static final int CHAR = 6;
  public static final int PUNTOYCOMA = 44;
  public static final int ENTERO = 60;
  public static final int DOUBLE = 5;
  public static final int RESTA = 28;
  public static final int CONTINUE = 17;
  public static final int COMENTARIO_LINEAS = 52;
  public static final int INT = 2;
  public static final int COMENTARIO_LINEA = 51;
  public static final int FOR = 13;
  public static final int NOT = 42;
  public static final int AND = 40;
  public static final int IGUAL = 34;
  public static final int CORCHETE_CIERRE = 50;
  public static final int CARACTER = 57;
  public static final int OR = 41;
  public static final int BOOL = 7;
  public static final int A_RESTA = 23;
  public static final int INCREMENTO = 32;
  public static final int SUMA = 27;
  public static final int IF = 10;
  public static final int LITERAL_CARACTER = 54;
  public static final int ID = 55;
  public static final int LITERAL_CADENA = 53;
  public static final int DECIMAL = 59;
  public static final int BOOLEAN = 58;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int CORCHETE_APERTURA = 49;
  public static final int DECREMENTO = 33;
  public static final int error = 1;
  public static final int COMA = 43;
  public static final int A_MULTIPLICACION = 25;
  public static final int CADENA = 56;
  public static final int MODULO = 31;
  public static final int MENOR = 37;
  public static final int TRY = 19;
  public static final int BREAK = 16;
  public static final int VOID = 8;
  public static final int ASIGNACION = 21;
  public static final int SWITCH = 12;
  public static final int MAYOR = 36;
  public static final int ELSE = 11;
  public static final int LLAVE_APERTURA = 45;
  public static final int WHILE = 14;
  public static final int MAYOR_IGUAL = 38;
  public static final int FLOAT = 4;
  public static final int LLAVE_CIERRE = 46;
  public static final int LONG = 3;
  public static final int STRING = 9;
  public static final int PARENTESIS_APERTURA = 47;
  public static final int A_DIVISION = 26;
  public static final int A_MODULO = 24;
  public static final int MENOR_IGUAL = 39;
  public static final int DIVISION = 30;
  public static final int A_SUMA = 22;
  public static final int DO = 15;
  public static final int MULTIPLICACION = 29;
  public static final int CATCH = 20;
}

