
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 25 03:19:37 CST 2025
//----------------------------------------------------

package act2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOL = 28;
  public static final int DIVISION = 38;
  public static final int COMENTARIO_LINEAS = 72;
  public static final int MENOR_IGUAL = 45;
  public static final int LITERAL_CARACTER = 65;
  public static final int PARENTESIS_CIERRE = 51;
  public static final int DIFERENCIA = 42;
  public static final int MAYOR = 44;
  public static final int COMENTARIO_LINEA = 71;
  public static final int CORCHETE_APERTURA = 54;
  public static final int CATCH = 23;
  public static final int LITERAL_CADENA = 64;
  public static final int DOUBLE = 27;
  public static final int PROTECTED = 5;
  public static final int NOT = 47;
  public static final int ERROR = 73;
  public static final int FLOAT = 25;
  public static final int DOS_PUNTOS = 58;
  public static final int CLASS = 2;
  public static final int LLAVE_CIERRE = 53;
  public static final int INCREMENTO = 33;
  public static final int COMA = 56;
  public static final int ENTERO = 62;
  public static final int MODULO = 39;
  public static final int LONG = 26;
  public static final int IGUAL = 41;
  public static final int QUESTION = 60;
  public static final int WHILE = 10;
  public static final int DECIMAL = 63;
  public static final int CHAR = 29;
  public static final int BOOLEAN = 32;
  public static final int PUNTOYCOMA = 57;
  public static final int SWITCH = 13;
  public static final int DO = 12;
  public static final int FOR = 11;
  public static final int VOID = 7;
  public static final int DECREMENTO = 34;
  public static final int PUBLIC = 3;
  public static final int RETURN = 18;
  public static final int A_MULTIPLICACION = 68;
  public static final int ELSE = 9;
  public static final int TRY = 22;
  public static final int MENOR = 43;
  public static final int BREAK = 16;
  public static final int LEXICAL_ERROR = 75;
  public static final int INT = 24;
  public static final int NULL = 31;
  public static final int EOF = 0;
  public static final int PUNTO = 59;
  public static final int THIS = 21;
  public static final int DEFAULT = 15;
  public static final int SUMA = 35;
  public static final int PRINT = 19;
  public static final int LLAVE_APERTURA = 52;
  public static final int OR = 49;
  public static final int error = 1;
  public static final int RESTA = 36;
  public static final int CONTINUE = 17;
  public static final int IF = 8;
  public static final int ID = 61;
  public static final int PARENTESIS_APERTURA = 50;
  public static final int A_MODULO = 70;
  public static final int MULTIPLICACION = 37;
  public static final int ASIGNACION = 40;
  public static final int CASE = 14;
  public static final int IFX = 74;
  public static final int NEW = 20;
  public static final int STRING = 30;
  public static final int A_DIVISION = 69;
  public static final int AND = 48;
  public static final int CORCHETE_CIERRE = 55;
  public static final int PRIVATE = 4;
  public static final int STATIC = 6;
  public static final int A_RESTA = 67;
  public static final int A_SUMA = 66;
  public static final int MAYOR_IGUAL = 46;
}

