
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 22 15:01:02 CDT 2025
//----------------------------------------------------

package act2;

import java_cup.runtime.*;
import java.io.*;
import java.util.HashMap;
import java.util.Stack;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Oct 22 15:01:02 CDT 2025
  */
public class Sintactico extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintactico() {super();}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\125\000\002\002\004\000\002\002\003\000\002\002" +
    "\002\000\002\003\004\000\002\003\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\005\010\000" +
    "\002\005\007\000\002\006\003\000\002\006\002\000\002" +
    "\007\004\000\002\007\003\000\002\010\003\000\002\010" +
    "\003\000\002\037\002\000\002\011\013\000\002\040\002" +
    "\000\002\011\013\000\002\012\003\000\002\012\002\000" +
    "\002\013\005\000\002\013\003\000\002\014\004\000\002" +
    "\015\003\000\002\015\003\000\002\015\003\000\002\015" +
    "\003\000\002\015\003\000\002\016\005\000\002\017\003" +
    "\000\002\020\005\000\002\020\003\000\002\021\003\000" +
    "\002\021\005\000\002\023\003\000\002\023\002\000\002" +
    "\024\004\000\002\024\003\000\002\041\002\000\002\022" +
    "\006\000\002\022\003\000\002\022\003\000\002\022\003" +
    "\000\002\022\003\000\002\022\003\000\002\022\003\000" +
    "\002\022\003\000\002\025\007\000\002\025\011\000\002" +
    "\026\007\000\002\027\013\000\002\033\004\000\002\033" +
    "\005\000\002\033\002\000\002\034\003\000\002\034\002" +
    "\000\002\035\005\000\002\035\002\000\002\031\006\000" +
    "\002\030\005\000\002\030\004\000\002\032\004\000\002" +
    "\036\003\000\002\036\003\000\002\036\003\000\002\036" +
    "\003\000\002\036\003\000\002\036\003\000\002\036\005" +
    "\000\002\036\005\000\002\036\005\000\002\036\005\000" +
    "\002\036\005\000\002\036\005\000\002\036\005\000\002" +
    "\036\005\000\002\036\005\000\002\036\005\000\002\036" +
    "\005\000\002\036\005\000\002\036\004\000\002\036\005" +
    "\000\002\036\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\226\000\022\002\uffff\004\020\011\011\027\006\030" +
    "\017\033\007\034\016\035\012\001\002\000\004\002\230" +
    "\001\002\000\022\002\ufffa\004\ufffa\011\ufffa\027\ufffa\030" +
    "\ufffa\033\ufffa\034\ufffa\035\ufffa\001\002\000\004\074\uffe8" +
    "\001\002\000\004\074\uffe4\001\002\000\022\002\ufffb\004" +
    "\ufffb\011\ufffb\027\ufffb\030\ufffb\033\ufffb\034\ufffb\035\ufffb" +
    "\001\002\000\004\074\220\001\002\000\004\074\uffe5\001" +
    "\002\000\022\002\ufffd\004\ufffd\011\ufffd\027\ufffd\030\ufffd" +
    "\033\ufffd\034\ufffd\035\ufffd\001\002\000\022\002\000\004" +
    "\020\011\011\027\006\030\017\033\007\034\016\035\012" +
    "\001\002\000\004\074\034\001\002\000\004\074\uffe6\001" +
    "\002\000\004\074\uffe7\001\002\000\004\074\022\001\002" +
    "\000\022\002\ufffc\004\ufffc\011\ufffc\027\ufffc\030\ufffc\033" +
    "\ufffc\034\ufffc\035\ufffc\001\002\000\004\063\023\001\002" +
    "\000\020\011\011\027\006\030\017\033\007\034\016\035" +
    "\012\064\ufff6\001\002\000\020\011\ufff2\027\ufff2\030\ufff2" +
    "\033\ufff2\034\ufff2\035\ufff2\064\ufff2\001\002\000\020\011" +
    "\011\027\006\030\017\033\007\034\016\035\012\064\ufff7" +
    "\001\002\000\020\011\ufff3\027\ufff3\030\ufff3\033\ufff3\034" +
    "\ufff3\035\ufff3\064\ufff3\001\002\000\004\064\031\001\002" +
    "\000\020\011\ufff4\027\ufff4\030\ufff4\033\ufff4\034\ufff4\035" +
    "\ufff4\064\ufff4\001\002\000\024\002\ufff8\004\ufff8\011\ufff8" +
    "\027\ufff8\030\ufff8\033\ufff8\034\ufff8\035\ufff8\070\032\001" +
    "\002\000\022\002\ufff9\004\ufff9\011\ufff9\027\ufff9\030\ufff9" +
    "\033\ufff9\034\ufff9\035\ufff9\001\002\000\020\011\ufff5\027" +
    "\ufff5\030\ufff5\033\ufff5\034\ufff5\035\ufff5\064\ufff5\001\002" +
    "\000\012\047\044\061\113\067\uffdf\070\uffdf\001\002\000" +
    "\006\067\041\070\uffe2\001\002\000\006\067\uffe0\070\uffe0" +
    "\001\002\000\004\070\040\001\002\000\060\002\uffe3\004" +
    "\uffe3\011\uffe3\012\uffe3\013\uffe3\014\uffe3\015\uffe3\024\uffe3" +
    "\027\uffe3\030\uffe3\033\uffe3\034\uffe3\035\uffe3\037\uffe3\056" +
    "\uffe3\061\uffe3\063\uffe3\064\uffe3\074\uffe3\075\uffe3\076\uffe3" +
    "\103\uffe3\104\uffe3\001\002\000\004\074\042\001\002\000" +
    "\010\047\044\067\uffdf\070\uffdf\001\002\000\006\067\uffe1" +
    "\070\uffe1\001\002\000\022\037\050\056\053\061\055\074" +
    "\052\075\047\076\046\103\045\104\054\001\002\000\042" +
    "\042\uffbf\043\uffbf\044\uffbf\045\uffbf\046\uffbf\050\uffbf\051" +
    "\uffbf\052\uffbf\053\uffbf\054\uffbf\055\uffbf\057\uffbf\060\uffbf" +
    "\062\uffbf\067\uffbf\070\uffbf\001\002\000\042\042\uffc0\043" +
    "\uffc0\044\uffc0\045\uffc0\046\uffc0\050\uffc0\051\uffc0\052\uffc0" +
    "\053\uffc0\054\uffc0\055\uffc0\057\uffc0\060\uffc0\062\uffc0\067" +
    "\uffc0\070\uffc0\001\002\000\042\042\uffc1\043\uffc1\044\uffc1" +
    "\045\uffc1\046\uffc1\050\uffc1\051\uffc1\052\uffc1\053\uffc1\054" +
    "\uffc1\055\uffc1\057\uffc1\060\uffc1\062\uffc1\067\uffc1\070\uffc1" +
    "\001\002\000\042\042\uffbd\043\uffbd\044\uffbd\045\uffbd\046" +
    "\uffbd\050\uffbd\051\uffbd\052\uffbd\053\uffbd\054\uffbd\055\uffbd" +
    "\057\uffbd\060\uffbd\062\uffbd\067\uffbd\070\uffbd\001\002\000" +
    "\040\042\061\043\072\044\063\045\070\046\066\050\067" +
    "\051\064\052\060\053\065\054\074\055\062\057\057\060" +
    "\073\067\uffde\070\uffde\001\002\000\042\042\uffbc\043\uffbc" +
    "\044\uffbc\045\uffbc\046\uffbc\050\uffbc\051\uffbc\052\uffbc\053" +
    "\uffbc\054\uffbc\055\uffbc\057\uffbc\060\uffbc\062\uffbc\067\uffbc" +
    "\070\uffbc\001\002\000\022\037\050\056\053\061\055\074" +
    "\052\075\047\076\046\103\045\104\054\001\002\000\042" +
    "\042\uffbe\043\uffbe\044\uffbe\045\uffbe\046\uffbe\050\uffbe\051" +
    "\uffbe\052\uffbe\053\uffbe\054\uffbe\055\uffbe\057\uffbe\060\uffbe" +
    "\062\uffbe\067\uffbe\070\uffbe\001\002\000\022\037\050\056" +
    "\053\061\055\074\052\075\047\076\046\103\045\104\054" +
    "\001\002\000\036\042\061\043\072\044\063\045\070\046" +
    "\066\050\067\051\064\052\060\053\065\054\074\055\062" +
    "\057\057\060\073\062\071\001\002\000\022\037\050\056" +
    "\053\061\055\074\052\075\047\076\046\103\045\104\054" +
    "\001\002\000\022\037\050\056\053\061\055\074\052\075" +
    "\047\076\046\103\045\104\054\001\002\000\022\037\050" +
    "\056\053\061\055\074\052\075\047\076\046\103\045\104" +
    "\054\001\002\000\022\037\050\056\053\061\055\074\052" +
    "\075\047\076\046\103\045\104\054\001\002\000\022\037" +
    "\050\056\053\061\055\074\052\075\047\076\046\103\045" +
    "\104\054\001\002\000\022\037\050\056\053\061\055\074" +
    "\052\075\047\076\046\103\045\104\054\001\002\000\022" +
    "\037\050\056\053\061\055\074\052\075\047\076\046\103" +
    "\045\104\054\001\002\000\022\037\050\056\053\061\055" +
    "\074\052\075\047\076\046\103\045\104\054\001\002\000" +
    "\022\037\050\056\053\061\055\074\052\075\047\076\046" +
    "\103\045\104\054\001\002\000\022\037\050\056\053\061" +
    "\055\074\052\075\047\076\046\103\045\104\054\001\002" +
    "\000\042\042\uffb6\043\uffb6\044\uffb6\045\uffb6\046\uffb6\050" +
    "\uffb6\051\uffb6\052\uffb6\053\uffb6\054\uffb6\055\uffb6\057\uffb6" +
    "\060\uffb6\062\uffb6\067\uffb6\070\uffb6\001\002\000\022\037" +
    "\050\056\053\061\055\074\052\075\047\076\046\103\045" +
    "\104\054\001\002\000\022\037\050\056\053\061\055\074" +
    "\052\075\047\076\046\103\045\104\054\001\002\000\022" +
    "\037\050\056\053\061\055\074\052\075\047\076\046\103" +
    "\045\104\054\001\002\000\026\042\061\043\072\044\063" +
    "\045\070\046\066\057\057\060\073\062\uffb1\067\uffb1\070" +
    "\uffb1\001\002\000\042\042\061\043\072\044\063\045\070" +
    "\046\066\050\uffad\051\uffad\052\uffad\053\uffad\054\uffad\055" +
    "\uffad\057\057\060\uffad\062\uffad\067\uffad\070\uffad\001\002" +
    "\000\042\042\uffba\043\uffba\044\063\045\070\046\066\050" +
    "\uffba\051\uffba\052\uffba\053\uffba\054\uffba\055\uffba\057\uffba" +
    "\060\uffba\062\uffba\067\uffba\070\uffba\001\002\000\042\042" +
    "\uffb8\043\uffb8\044\uffb8\045\uffb8\046\uffb8\050\uffb8\051\uffb8" +
    "\052\uffb8\053\uffb8\054\uffb8\055\uffb8\057\uffb8\060\uffb8\062" +
    "\uffb8\067\uffb8\070\uffb8\001\002\000\026\042\061\043\072" +
    "\044\063\045\070\046\066\057\057\060\073\062\uffb5\067" +
    "\uffb5\070\uffb5\001\002\000\042\042\uffb7\043\uffb7\044\uffb7" +
    "\045\uffb7\046\uffb7\050\uffb7\051\uffb7\052\uffb7\053\uffb7\054" +
    "\uffb7\055\uffb7\057\uffb7\060\uffb7\062\uffb7\067\uffb7\070\uffb7" +
    "\001\002\000\026\042\061\043\072\044\063\045\070\046" +
    "\066\057\057\060\073\062\uffb2\067\uffb2\070\uffb2\001\002" +
    "\000\026\042\061\043\072\044\063\045\070\046\066\057" +
    "\057\060\073\062\uffb4\067\uffb4\070\uffb4\001\002\000\042" +
    "\042\uffb9\043\uffb9\044\uffb9\045\uffb9\046\uffb9\050\uffb9\051" +
    "\uffb9\052\uffb9\053\uffb9\054\uffb9\055\uffb9\057\uffb9\060\uffb9" +
    "\062\uffb9\067\uffb9\070\uffb9\001\002\000\026\042\061\043" +
    "\072\044\063\045\070\046\066\057\057\060\073\062\uffb0" +
    "\067\uffb0\070\uffb0\001\002\000\042\042\uffbb\043\uffbb\044" +
    "\063\045\070\046\066\050\uffbb\051\uffbb\052\uffbb\053\uffbb" +
    "\054\uffbb\055\uffbb\057\uffbb\060\uffbb\062\uffbb\067\uffbb\070" +
    "\uffbb\001\002\000\026\042\061\043\072\044\063\045\070" +
    "\046\066\057\057\060\073\062\uffb3\067\uffb3\070\uffb3\001" +
    "\002\000\042\042\061\043\072\044\063\045\070\046\066" +
    "\050\uffae\051\uffae\052\uffae\053\uffae\054\uffae\055\uffae\057" +
    "\uffae\060\uffae\062\uffae\067\uffae\070\uffae\001\002\000\042" +
    "\042\uffaf\043\uffaf\044\uffaf\045\uffaf\046\uffaf\050\uffaf\051" +
    "\uffaf\052\uffaf\053\uffaf\054\uffaf\055\uffaf\057\uffaf\060\uffaf" +
    "\062\uffaf\067\uffaf\070\uffaf\001\002\000\016\027\006\030" +
    "\017\033\007\034\016\035\012\062\uffec\001\002\000\006" +
    "\062\uffea\067\uffea\001\002\000\004\062\123\001\002\000" +
    "\004\074\122\001\002\000\006\062\uffed\067\120\001\002" +
    "\000\014\027\006\030\017\033\007\034\016\035\012\001" +
    "\002\000\006\062\uffeb\067\uffeb\001\002\000\006\062\uffe9" +
    "\067\uffe9\001\002\000\004\063\124\001\002\000\050\012" +
    "\ufff1\014\ufff1\015\ufff1\024\ufff1\027\ufff1\030\ufff1\033\ufff1" +
    "\034\ufff1\035\ufff1\037\ufff1\056\ufff1\061\ufff1\063\ufff1\064" +
    "\ufff1\074\ufff1\075\ufff1\076\ufff1\103\ufff1\104\ufff1\001\002" +
    "\000\050\012\136\014\127\015\146\024\135\027\006\030" +
    "\017\033\007\034\016\035\012\037\050\056\053\061\055" +
    "\063\145\064\uffdc\074\140\075\047\076\046\103\045\104" +
    "\054\001\002\000\052\012\uffd1\013\uffd1\014\uffd1\015\uffd1" +
    "\024\uffd1\027\uffd1\030\uffd1\033\uffd1\034\uffd1\035\uffd1\037" +
    "\uffd1\056\uffd1\061\uffd1\063\uffd1\064\uffd1\074\uffd1\075\uffd1" +
    "\076\uffd1\103\uffd1\104\uffd1\001\002\000\004\061\213\001" +
    "\002\000\052\012\uffd2\013\uffd2\014\uffd2\015\uffd2\024\uffd2" +
    "\027\uffd2\030\uffd2\033\uffd2\034\uffd2\035\uffd2\037\uffd2\056" +
    "\uffd2\061\uffd2\063\uffd2\064\uffd2\074\uffd2\075\uffd2\076\uffd2" +
    "\103\uffd2\104\uffd2\001\002\000\050\012\136\014\127\015" +
    "\146\024\135\027\006\030\017\033\007\034\016\035\012" +
    "\037\050\056\053\061\055\063\145\064\uffdd\074\140\075" +
    "\047\076\046\103\045\104\054\001\002\000\036\042\061" +
    "\043\072\044\063\045\070\046\066\050\067\051\064\052" +
    "\060\053\065\054\074\055\062\057\057\060\073\070\211" +
    "\001\002\000\004\064\210\001\002\000\052\012\uffd7\013" +
    "\uffd7\014\uffd7\015\uffd7\024\uffd7\027\uffd7\030\uffd7\033\uffd7" +
    "\034\uffd7\035\uffd7\037\uffd7\056\uffd7\061\uffd7\063\uffd7\064" +
    "\uffd7\074\uffd7\075\uffd7\076\uffd7\103\uffd7\104\uffd7\001\002" +
    "\000\024\037\050\056\053\061\055\070\206\074\052\075" +
    "\047\076\046\103\045\104\054\001\002\000\004\061\177" +
    "\001\002\000\004\074\042\001\002\000\040\042\uffbc\043" +
    "\uffbc\044\uffbc\045\uffbc\046\uffbc\047\174\050\uffbc\051\uffbc" +
    "\052\uffbc\053\uffbc\054\uffbc\055\uffbc\057\uffbc\060\uffbc\070" +
    "\uffbc\001\002\000\050\012\uffda\014\uffda\015\uffda\024\uffda" +
    "\027\uffda\030\uffda\033\uffda\034\uffda\035\uffda\037\uffda\056" +
    "\uffda\061\uffda\063\uffda\064\uffda\074\uffda\075\uffda\076\uffda" +
    "\103\uffda\104\uffda\001\002\000\052\012\uffd5\013\uffd5\014" +
    "\uffd5\015\uffd5\024\uffd5\027\uffd5\030\uffd5\033\uffd5\034\uffd5" +
    "\035\uffd5\037\uffd5\056\uffd5\061\uffd5\063\uffd5\064\uffd5\074" +
    "\uffd5\075\uffd5\076\uffd5\103\uffd5\104\uffd5\001\002\000\052" +
    "\012\uffd3\013\uffd3\014\uffd3\015\uffd3\024\uffd3\027\uffd3\030" +
    "\uffd3\033\uffd3\034\uffd3\035\uffd3\037\uffd3\056\uffd3\061\uffd3" +
    "\063\uffd3\064\uffd3\074\uffd3\075\uffd3\076\uffd3\103\uffd3\104" +
    "\uffd3\001\002\000\052\012\uffd6\013\uffd6\014\uffd6\015\uffd6" +
    "\024\uffd6\027\uffd6\030\uffd6\033\uffd6\034\uffd6\035\uffd6\037" +
    "\uffd6\056\uffd6\061\uffd6\063\uffd6\064\uffd6\074\uffd6\075\uffd6" +
    "\076\uffd6\103\uffd6\104\uffd6\001\002\000\050\012\uffd9\014" +
    "\uffd9\015\uffd9\024\uffd9\027\uffd9\030\uffd9\033\uffd9\034\uffd9" +
    "\035\uffd9\037\uffd9\056\uffd9\061\uffd9\063\uffd9\064\uffd9\074" +
    "\uffd9\075\uffd9\076\uffd9\103\uffd9\104\uffd9\001\002\000\004" +
    "\061\150\001\002\000\052\012\uffd4\013\uffd4\014\uffd4\015" +
    "\uffd4\024\uffd4\027\uffd4\030\uffd4\033\uffd4\034\uffd4\035\uffd4" +
    "\037\uffd4\056\uffd4\061\uffd4\063\uffd4\064\uffd4\074\uffd4\075" +
    "\uffd4\076\uffd4\103\uffd4\104\uffd4\001\002\000\020\027\006" +
    "\030\017\033\007\034\016\035\012\070\uffca\074\151\001" +
    "\002\000\004\047\167\001\002\000\004\074\042\001\002" +
    "\000\004\070\154\001\002\000\024\037\050\056\053\061" +
    "\055\070\uffc8\074\052\075\047\076\046\103\045\104\054" +
    "\001\002\000\004\070\157\001\002\000\036\042\061\043" +
    "\072\044\063\045\070\046\066\050\067\051\064\052\060" +
    "\053\065\054\074\055\062\057\057\060\073\070\uffc9\001" +
    "\002\000\006\062\uffc6\074\160\001\002\000\004\047\164" +
    "\001\002\000\004\062\162\001\002\000\046\012\136\014" +
    "\127\015\146\024\135\027\006\030\017\033\007\034\016" +
    "\035\012\037\050\056\053\061\055\063\145\074\140\075" +
    "\047\076\046\103\045\104\054\001\002\000\052\012\uffcd" +
    "\013\uffcd\014\uffcd\015\uffcd\024\uffcd\027\uffcd\030\uffcd\033" +
    "\uffcd\034\uffcd\035\uffcd\037\uffcd\056\uffcd\061\uffcd\063\uffcd" +
    "\064\uffcd\074\uffcd\075\uffcd\076\uffcd\103\uffcd\104\uffcd\001" +
    "\002\000\022\037\050\056\053\061\055\074\052\075\047" +
    "\076\046\103\045\104\054\001\002\000\036\042\061\043" +
    "\072\044\063\045\070\046\066\050\067\051\064\052\060" +
    "\053\065\054\074\055\062\057\057\060\073\062\uffc7\001" +
    "\002\000\004\070\uffcc\001\002\000\022\037\050\056\053" +
    "\061\055\074\052\075\047\076\046\103\045\104\054\001" +
    "\002\000\036\042\061\043\072\044\063\045\070\046\066" +
    "\050\067\051\064\052\060\053\065\054\074\055\062\057" +
    "\057\060\073\070\uffcb\001\002\000\050\012\136\014\127" +
    "\015\146\024\135\027\006\030\017\033\007\034\016\035" +
    "\012\037\050\056\053\061\055\063\145\064\uffdc\074\140" +
    "\075\047\076\046\103\045\104\054\001\002\000\004\064" +
    "\173\001\002\000\052\012\uffd8\013\uffd8\014\uffd8\015\uffd8" +
    "\024\uffd8\027\uffd8\030\uffd8\033\uffd8\034\uffd8\035\uffd8\037" +
    "\uffd8\056\uffd8\061\uffd8\063\uffd8\064\uffd8\074\uffd8\075\uffd8" +
    "\076\uffd8\103\uffd8\104\uffd8\001\002\000\022\037\050\056" +
    "\053\061\055\074\052\075\047\076\046\103\045\104\054" +
    "\001\002\000\036\042\061\043\072\044\063\045\070\046" +
    "\066\050\067\051\064\052\060\053\065\054\074\055\062" +
    "\057\057\060\073\070\176\001\002\000\052\012\uffc5\013" +
    "\uffc5\014\uffc5\015\uffc5\024\uffc5\027\uffc5\030\uffc5\033\uffc5" +
    "\034\uffc5\035\uffc5\037\uffc5\056\uffc5\061\uffc5\063\uffc5\064" +
    "\uffc5\074\uffc5\075\uffc5\076\uffc5\103\uffc5\104\uffc5\001\002" +
    "\000\022\037\050\056\053\061\055\074\052\075\047\076" +
    "\046\103\045\104\054\001\002\000\036\042\061\043\072" +
    "\044\063\045\070\046\066\050\067\051\064\052\060\053" +
    "\065\054\074\055\062\057\057\060\073\062\201\001\002" +
    "\000\046\012\136\014\127\015\146\024\135\027\006\030" +
    "\017\033\007\034\016\035\012\037\050\056\053\061\055" +
    "\063\145\074\140\075\047\076\046\103\045\104\054\001" +
    "\002\000\052\012\uffd0\013\uffd0\014\uffd0\015\uffd0\024\uffd0" +
    "\027\uffd0\030\uffd0\033\uffd0\034\uffd0\035\uffd0\037\uffd0\056" +
    "\uffd0\061\uffd0\063\uffd0\064\uffd0\074\uffd0\075\uffd0\076\uffd0" +
    "\103\uffd0\104\uffd0\001\002\000\046\012\136\014\127\015" +
    "\146\024\135\027\006\030\017\033\007\034\016\035\012" +
    "\037\050\056\053\061\055\063\145\074\140\075\047\076" +
    "\046\103\045\104\054\001\002\000\052\012\uffcf\013\uffcf" +
    "\014\uffcf\015\uffcf\024\uffcf\027\uffcf\030\uffcf\033\uffcf\034" +
    "\uffcf\035\uffcf\037\uffcf\056\uffcf\061\uffcf\063\uffcf\064\uffcf" +
    "\074\uffcf\075\uffcf\076\uffcf\103\uffcf\104\uffcf\001\002\000" +
    "\036\042\061\043\072\044\063\045\070\046\066\050\067" +
    "\051\064\052\060\053\065\054\074\055\062\057\057\060" +
    "\073\070\207\001\002\000\052\012\uffc3\013\uffc3\014\uffc3" +
    "\015\uffc3\024\uffc3\027\uffc3\030\uffc3\033\uffc3\034\uffc3\035" +
    "\uffc3\037\uffc3\056\uffc3\061\uffc3\063\uffc3\064\uffc3\074\uffc3" +
    "\075\uffc3\076\uffc3\103\uffc3\104\uffc3\001\002\000\052\012" +
    "\uffc4\013\uffc4\014\uffc4\015\uffc4\024\uffc4\027\uffc4\030\uffc4" +
    "\033\uffc4\034\uffc4\035\uffc4\037\uffc4\056\uffc4\061\uffc4\063" +
    "\uffc4\064\uffc4\074\uffc4\075\uffc4\076\uffc4\103\uffc4\104\uffc4" +
    "\001\002\000\024\002\ufff0\004\ufff0\011\ufff0\027\ufff0\030" +
    "\ufff0\033\ufff0\034\ufff0\035\ufff0\064\ufff0\001\002\000\052" +
    "\012\uffc2\013\uffc2\014\uffc2\015\uffc2\024\uffc2\027\uffc2\030" +
    "\uffc2\033\uffc2\034\uffc2\035\uffc2\037\uffc2\056\uffc2\061\uffc2" +
    "\063\uffc2\064\uffc2\074\uffc2\075\uffc2\076\uffc2\103\uffc2\104" +
    "\uffc2\001\002\000\050\012\uffdb\014\uffdb\015\uffdb\024\uffdb" +
    "\027\uffdb\030\uffdb\033\uffdb\034\uffdb\035\uffdb\037\uffdb\056" +
    "\uffdb\061\uffdb\063\uffdb\064\uffdb\074\uffdb\075\uffdb\076\uffdb" +
    "\103\uffdb\104\uffdb\001\002\000\022\037\050\056\053\061" +
    "\055\074\052\075\047\076\046\103\045\104\054\001\002" +
    "\000\036\042\061\043\072\044\063\045\070\046\066\050" +
    "\067\051\064\052\060\053\065\054\074\055\062\057\057" +
    "\060\073\062\215\001\002\000\046\012\136\014\127\015" +
    "\146\024\135\027\006\030\017\033\007\034\016\035\012" +
    "\037\050\056\053\061\055\063\145\074\140\075\047\076" +
    "\046\103\045\104\054\001\002\000\052\012\uffce\013\uffce" +
    "\014\uffce\015\uffce\024\uffce\027\uffce\030\uffce\033\uffce\034" +
    "\uffce\035\uffce\037\uffce\056\uffce\061\uffce\063\uffce\064\uffce" +
    "\074\uffce\075\uffce\076\uffce\103\uffce\104\uffce\001\002\000" +
    "\022\002\ufffe\004\ufffe\011\ufffe\027\ufffe\030\ufffe\033\ufffe" +
    "\034\ufffe\035\ufffe\001\002\000\004\061\221\001\002\000" +
    "\016\027\006\030\017\033\007\034\016\035\012\062\uffec" +
    "\001\002\000\004\062\223\001\002\000\004\063\224\001" +
    "\002\000\050\012\uffef\014\uffef\015\uffef\024\uffef\027\uffef" +
    "\030\uffef\033\uffef\034\uffef\035\uffef\037\uffef\056\uffef\061" +
    "\uffef\063\uffef\064\uffef\074\uffef\075\uffef\076\uffef\103\uffef" +
    "\104\uffef\001\002\000\050\012\136\014\127\015\146\024" +
    "\135\027\006\030\017\033\007\034\016\035\012\037\050" +
    "\056\053\061\055\063\145\064\uffdc\074\140\075\047\076" +
    "\046\103\045\104\054\001\002\000\004\064\227\001\002" +
    "\000\024\002\uffee\004\uffee\011\uffee\027\uffee\030\uffee\033" +
    "\uffee\034\uffee\035\uffee\064\uffee\001\002\000\004\002\001" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\226\000\020\002\003\003\013\004\012\005\020\011" +
    "\007\015\014\016\004\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\004\216\005\020\011\007\015\014\016\004\001" +
    "\001\000\010\017\036\020\034\021\035\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\006\026\007\024\010\027" +
    "\011\025\015\014\016\023\001\001\000\002\001\001\000" +
    "\012\010\032\011\025\015\014\016\023\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\021\042\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\036\050\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\036\111\001" +
    "\001\000\002\001\001\000\004\036\055\001\001\000\002" +
    "\001\001\000\004\036\110\001\001\000\004\036\107\001" +
    "\001\000\004\036\106\001\001\000\004\036\105\001\001" +
    "\000\004\036\104\001\001\000\004\036\103\001\001\000" +
    "\004\036\102\001\001\000\004\036\101\001\001\000\004" +
    "\036\100\001\001\000\004\036\077\001\001\000\002\001" +
    "\001\000\004\036\076\001\001\000\004\036\075\001\001" +
    "\000\004\036\074\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\012" +
    "\114\013\116\014\113\015\115\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\014\120\015\115\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\037\124\001\001\000" +
    "\032\015\136\016\125\022\140\023\132\024\130\025\133" +
    "\026\143\027\141\030\146\031\142\032\127\036\131\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\026\015\136\016\125\022\211\025\133\026\143\027" +
    "\141\030\146\031\142\032\127\036\131\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\036" +
    "\204\001\001\000\002\001\001\000\010\017\036\020\034" +
    "\021\035\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\041\170\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\015\151\033\152\001\001\000\002\001\001\000\010" +
    "\017\165\020\034\021\035\001\001\000\002\001\001\000" +
    "\006\034\154\036\155\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\035\160\001\001\000\002\001\001\000" +
    "\002\001\001\000\026\015\136\016\125\022\162\025\133" +
    "\026\143\027\141\030\146\031\142\032\127\036\131\001" +
    "\001\000\002\001\001\000\004\036\164\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\036\167\001\001\000" +
    "\002\001\001\000\032\015\136\016\125\022\140\023\171" +
    "\024\130\025\133\026\143\027\141\030\146\031\142\032" +
    "\127\036\131\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\036\174\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\036\177\001\001\000\002\001\001\000\026" +
    "\015\136\016\125\022\201\025\133\026\143\027\141\030" +
    "\146\031\142\032\127\036\131\001\001\000\002\001\001" +
    "\000\026\015\136\016\125\022\203\025\133\026\143\027" +
    "\141\030\146\031\142\032\127\036\131\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\036\213\001\001\000\002\001\001\000\026\015" +
    "\136\016\125\022\215\025\133\026\143\027\141\030\146" +
    "\031\142\032\127\036\131\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\012\221\013\116" +
    "\014\113\015\115\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\040\224\001\001\000\032\015\136\016\125" +
    "\022\140\023\225\024\130\025\133\026\143\027\141\030" +
    "\146\031\142\032\127\036\131\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
 __init__(); 
    }


    protected java_cup.runtime.Symbol lastErrorToken;

    public static final String T_INT="int", T_FLOAT="float", T_CHAR="char", T_STRING="string", T_BOOL="bool";

    public static class SymbolInfo {
        public String tipo, alcance; public Object valor; public int linea, columna;
        public SymbolInfo(String tipo, String alcance, int linea, int columna, Object valor){
            this.tipo=tipo; this.alcance=alcance; this.linea=linea; this.columna=columna; this.valor=valor;
        }
    }

    public java.util.Stack<java.util.HashMap<String, SymbolInfo>> tablaDeSimbolos;
    public String alcanceActual = "global";
    public String tipoActualDecl = null;
    public String tipoFuncionActual = null;
    public int erroresSem = 0, erroresSint = 0;

    public void __init__() {
        tablaDeSimbolos = new java.util.Stack<>();
        iniciarAmbito();
    }

    public void iniciarAmbito(){
        if (tablaDeSimbolos==null) tablaDeSimbolos = new java.util.Stack<>();
        tablaDeSimbolos.push(new java.util.HashMap<>());
    }
    public void finalizarAmbito(){ if(!tablaDeSimbolos.isEmpty()) tablaDeSimbolos.pop(); }

    public void insertarSimbolo(String id, String tipo) {
        if (tablaDeSimbolos.isEmpty()) iniciarAmbito();
        var amb = tablaDeSimbolos.peek();
        if (amb.containsKey(id)) {
            report_semantic_error("Error: identificador '"+id+"' ya declarado en este ámbito.", null);
        } else {
            amb.put(id, new SymbolInfo(tipo, alcanceActual, -1, -1, null));
        }
    }
    public void insertarSimbolo(String id, String tipo, Object unused) { insertarSimbolo(id, tipo); }

    public SymbolInfo buscarSimboloInfo(String id){
        for(int i=tablaDeSimbolos.size()-1;i>=0;i--){
            var amb = tablaDeSimbolos.get(i);
            if (amb.containsKey(id)) return amb.get(id);
        }
        return null;
    }
    public String tipoDe(String id){
        var info = buscarSimboloInfo(id);
        return (info==null)? null : info.tipo;
    }

    public boolean tiposCompatibles(String destino, String fuente){
        if (destino==null || fuente==null) return false;
        if (destino.equals(fuente)) return true;
        if (destino.equals(T_FLOAT) && fuente.equals(T_INT)) return true;
        return false;
    }

    public void report_semantic_error(String msg, Object info){
        erroresSem++;
        if (info instanceof java_cup.runtime.Symbol s){
            System.err.println(msg+" Línea "+(s.left+1)+", Columna "+(s.right+1));
        } else System.err.println(msg);
    }
    public void report_expected(String esp, java_cup.runtime.Symbol enc){
        erroresSint++;
        String m="Error sintáctico: se esperaba "+esp+".";
        if(enc!=null) m+=" Encontrado '"+enc.value+"' en "+(enc.left+1)+":"+ (enc.right+1);
        System.err.println(m);
    }
    public void syntax_error(java_cup.runtime.Symbol tok){
        erroresSint++;
        String m="Error sintáctico: token inesperado";
        if(tok!=null && tok.value!=null) m+=" '"+tok.value+"'";
        System.err.println(m);
    }
    public void report_error(String m, Object info){
        erroresSint++;
        System.err.println(m);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintactico$actions {
  private final Sintactico parser;

  /** Constructor */
  CUP$Sintactico$actions(Sintactico parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // expresion ::= expresion OR expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = "bool"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // expresion ::= expresion AND expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = "bool"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // expresion ::= NOT expresion 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = "bool"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // expresion ::= expresion MAYOR_IGUAL expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = "bool"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // expresion ::= expresion MENOR_IGUAL expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = "bool"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // expresion ::= expresion MAYOR expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = "bool"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // expresion ::= expresion MENOR expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = "bool"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // expresion ::= expresion DIFERENCIA expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = "bool"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // expresion ::= expresion IGUAL expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = "bool"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // expresion ::= PARENTESIS_APERTURA expresion PARENTESIS_CIERRE 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = e; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // expresion ::= expresion MODULO expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = "int";   
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expresion ::= expresion DIVISION expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = "float"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expresion ::= expresion MULTIPLICACION expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
          RESULT = (e1.equals("float") || e2.equals("float")) ? "float" : "int";
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expresion ::= expresion RESTA expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
          RESULT = (e1.equals("float") || e2.equals("float")) ? "float" : "int";
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expresion ::= expresion SUMA expresion 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
          RESULT = (e1.equals("string") || e2.equals("string")) ? "string"
                 : (e1.equals("float")  || e2.equals("float"))  ? "float" : "int";
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expresion ::= ID 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
          String t = parser.tipoDe((String)id);
          if (t==null){ parser.report_semantic_error("Error: identificador '"+id+"' no declarado.", null); RESULT="error_tipo"; }
          else RESULT = t;
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expresion ::= BOOLEAN 
            {
              String RESULT =null;
		 RESULT = "bool"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expresion ::= CARACTER 
            {
              String RESULT =null;
		 RESULT = "char"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expresion ::= CADENA 
            {
              String RESULT =null;
		 RESULT = "string"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expresion ::= DECIMAL 
            {
              String RESULT =null;
		 RESULT = "float"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expresion ::= ENTERO 
            {
              String RESULT =null;
		 RESULT = "int"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // sentencia_expr ::= expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_expr",24, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // sentencia_return ::= RETURN PUNTOYCOMA 
            {
              Object RESULT =null;
		
          if (parser.tipoFuncionActual!=null && !"void".equals(parser.tipoFuncionActual)){
              parser.report_semantic_error("Error: falta valor en return de función '"+parser.tipoFuncionActual+"'.", null);
          }
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_return",22, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // sentencia_return ::= RETURN expresion PUNTOYCOMA 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
          if (parser.tipoFuncionActual==null){
              parser.report_semantic_error("Error: 'return' fuera de una función.", null);
          } else if ("void".equals(parser.tipoFuncionActual)) {
              parser.report_semantic_error("Error: 'return' con valor en función void.", null);
          } else if (!parser.tiposCompatibles(parser.tipoFuncionActual, e)) {
              parser.report_semantic_error("Error: return incompatible. Esperado "+parser.tipoFuncionActual+", recibido "+e, null);
          }
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_return",22, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // sentencia_asignacion ::= ID ASIGNACION expresion PUNTOYCOMA 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int exprTleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int exprTright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String exprT = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
      String t = parser.tipoDe((String)id);
      if (t==null){
          parser.report_semantic_error("Error: identificador '"+id+"' no declarado.", null);
      } else if (!parser.tiposCompatibles(t, exprT)){
          parser.report_semantic_error("Error: tipo incompatible al asignar a '"+id+"'. Esperado "+t+", recibido "+exprT, null);
      }
   
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",23, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // for_actualizacion ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_actualizacion",27, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // for_actualizacion ::= ID ASIGNACION expresion 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int exprTleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int exprTright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String exprT = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
                        String t = parser.tipoDe((String)id);
                        if (t==null){
                            parser.report_semantic_error("Error: identificador '"+id+"' no declarado.", null);
                        } else if (!parser.tiposCompatibles(t, exprT)){
                            parser.report_semantic_error("Error: tipo incompatible al asignar a '"+id+"'. Esperado "+t+", recibido "+exprT, null);
                        }
                    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_actualizacion",27, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // for_condicion ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_condicion",26, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // for_condicion ::= expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_condicion",26, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // for_init ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_init",25, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // for_init ::= ID ASIGNACION expresion 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int exprTleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int exprTright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String exprT = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
                 String t = parser.tipoDe((String)id);
                 if (t==null){
                     parser.report_semantic_error("Error: identificador '"+id+"' no declarado.", null);
                 } else if (!parser.tiposCompatibles(t, exprT)){
                     parser.report_semantic_error("Error: tipo incompatible al asignar a '"+id+"'. Esperado "+t+", recibido "+exprT, null);
                 }
             
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_init",25, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // for_init ::= tipo_dato dec_variable_lista 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_init",25, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // sentencia_for ::= FOR PARENTESIS_APERTURA for_init PUNTOYCOMA for_condicion PUNTOYCOMA for_actualizacion PARENTESIS_CIERRE sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_for",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // sentencia_while ::= WHILE PARENTESIS_APERTURA expresion PARENTESIS_CIERRE sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_while",20, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // sentencia_if ::= IF PARENTESIS_APERTURA expresion PARENTESIS_CIERRE sentencia ELSE sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_if",19, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-6)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // sentencia_if ::= IF PARENTESIS_APERTURA expresion PARENTESIS_CIERRE sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_if",19, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // sentencia ::= dec_variable 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // sentencia ::= sentencia_expr 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // sentencia ::= sentencia_asignacion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // sentencia ::= sentencia_return 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // sentencia ::= sentencia_for 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // sentencia ::= sentencia_while 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // sentencia ::= sentencia_if 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // sentencia ::= LLAVE_APERTURA NT$2 bloque_sentencias LLAVE_CIERRE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		 parser.finalizarAmbito(); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // NT$2 ::= 
            {
              Object RESULT =null;
 parser.iniciarAmbito(); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("NT$2",31, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // lista_sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_sentencias",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_sentencias",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // bloque_sentencias ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("bloque_sentencias",17, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // bloque_sentencias ::= lista_sentencias 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("bloque_sentencias",17, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // id_con_asignacion_opcional ::= ID ASIGNACION expresion 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        if (!parser.tiposCompatibles(parser.tipoActualDecl, e)) {
            parser.report_semantic_error("Error: asignación incompatible a '"+id+"'. Esperado "+parser.tipoActualDecl+", recibido "+e, null);
        }
        parser.insertarSimbolo((String)id, parser.tipoActualDecl);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("id_con_asignacion_opcional",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // id_con_asignacion_opcional ::= ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 parser.insertarSimbolo((String)id, parser.tipoActualDecl); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("id_con_asignacion_opcional",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // lista_ids_con_asignacion ::= id_con_asignacion_opcional 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_ids_con_asignacion",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // lista_ids_con_asignacion ::= lista_ids_con_asignacion COMA id_con_asignacion_opcional 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_ids_con_asignacion",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // dec_variable_lista ::= lista_ids_con_asignacion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_variable_lista",13, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // dec_variable ::= tipo_dato dec_variable_lista PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_variable",12, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // tipo_dato ::= BOOL 
            {
              String RESULT =null;
		 parser.tipoActualDecl="bool";   RESULT="bool";   
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // tipo_dato ::= STRING 
            {
              String RESULT =null;
		 parser.tipoActualDecl="string"; RESULT="string"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // tipo_dato ::= CHAR 
            {
              String RESULT =null;
		 parser.tipoActualDecl="char";   RESULT="char";   
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipo_dato ::= FLOAT 
            {
              String RESULT =null;
		 parser.tipoActualDecl="float";  RESULT="float";  
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo_dato ::= INT 
            {
              String RESULT =null;
		 parser.tipoActualDecl="int";    RESULT="int";    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // parametro ::= tipo_dato ID 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("parametro",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // lista_parametros ::= parametro 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_parametros",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // lista_parametros ::= lista_parametros COMA parametro 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_parametros",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // lista_parametros_opcional ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_parametros_opcional",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // lista_parametros_opcional ::= lista_parametros 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_parametros_opcional",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // dec_funcion ::= VOID ID PARENTESIS_APERTURA lista_parametros_opcional PARENTESIS_CIERRE LLAVE_APERTURA NT$1 bloque_sentencias LLAVE_CIERRE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)).value;
		
        parser.finalizarAmbito();
        parser.alcanceActual = "global";
        parser.tipoFuncionActual = null;
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_funcion",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // NT$1 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).value;

        parser.insertarSimbolo((String)id,"void");
        parser.alcanceActual = "local";
        parser.tipoFuncionActual = "void";
        parser.iniciarAmbito();
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("NT$1",30, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // dec_funcion ::= tipo_dato ID PARENTESIS_APERTURA lista_parametros_opcional PARENTESIS_CIERRE LLAVE_APERTURA NT$0 bloque_sentencias LLAVE_CIERRE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)).value;
		
        parser.finalizarAmbito();
        parser.alcanceActual = "global";
        parser.tipoFuncionActual = null;
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_funcion",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // NT$0 ::= 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).value;

        parser.insertarSimbolo((String)id,t);
        parser.alcanceActual = "local";
        parser.tipoFuncionActual = t;
        parser.iniciarAmbito();
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("NT$0",29, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // miembro ::= dec_variable 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("miembro",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // miembro ::= dec_funcion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("miembro",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // lista_miembros ::= miembro 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_miembros",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_miembros ::= lista_miembros miembro 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_miembros",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // cuerpo_clase ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("cuerpo_clase",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // cuerpo_clase ::= lista_miembros 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("cuerpo_clase",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // dec_clase ::= CLASS ID LLAVE_APERTURA cuerpo_clase LLAVE_CIERRE 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_clase",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // dec_clase ::= CLASS ID LLAVE_APERTURA cuerpo_clase LLAVE_CIERRE PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_clase",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declaracion ::= dec_variable 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("declaracion",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declaracion ::= dec_funcion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("declaracion",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declaracion ::= dec_clase 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("declaracion",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_declaraciones ::= declaracion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_declaraciones",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_declaraciones ::= lista_declaraciones declaracion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_declaraciones",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= lista_declaraciones 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico$parser.done_parsing();
          return CUP$Sintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

