
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 06 16:21:12 CST 2025
//----------------------------------------------------

package act2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOL = 25;
  public static final int DIVISION = 35;
  public static final int COMENTARIO_LINEAS = 71;
  public static final int MENOR_IGUAL = 42;
  public static final int LITERAL_CARACTER = 62;
  public static final int PARENTESIS_CIERRE = 48;
  public static final int DIFERENCIA = 39;
  public static final int MAYOR = 41;
  public static final int COMENTARIO_LINEA = 70;
  public static final int CORCHETE_APERTURA = 51;
  public static final int CATCH = 73;
  public static final int LITERAL_CADENA = 61;
  public static final int DOUBLE = 24;
  public static final int PROTECTED = 5;
  public static final int NOT = 44;
  public static final int ERROR = 64;
  public static final int FLOAT = 22;
  public static final int DOS_PUNTOS = 55;
  public static final int CLASS = 2;
  public static final int LLAVE_CIERRE = 50;
  public static final int INCREMENTO = 30;
  public static final int COMA = 53;
  public static final int ENTERO = 59;
  public static final int MODULO = 36;
  public static final int LONG = 23;
  public static final int IGUAL = 38;
  public static final int QUESTION = 57;
  public static final int WHILE = 10;
  public static final int DECIMAL = 60;
  public static final int CHAR = 26;
  public static final int BOOLEAN = 29;
  public static final int PUNTOYCOMA = 54;
  public static final int SWITCH = 13;
  public static final int DO = 12;
  public static final int FOR = 11;
  public static final int VOID = 7;
  public static final int DECREMENTO = 31;
  public static final int PUBLIC = 3;
  public static final int RETURN = 18;
  public static final int A_MULTIPLICACION = 67;
  public static final int TRY = 72;
  public static final int ELSE = 9;
  public static final int MENOR = 40;
  public static final int BREAK = 16;
  public static final int INT = 21;
  public static final int NULL = 28;
  public static final int EOF = 0;
  public static final int PUNTO = 56;
  public static final int THIS = 20;
  public static final int DEFAULT = 15;
  public static final int SUMA = 32;
  public static final int LLAVE_APERTURA = 49;
  public static final int OR = 46;
  public static final int error = 1;
  public static final int RESTA = 33;
  public static final int CONTINUE = 17;
  public static final int IF = 8;
  public static final int ID = 58;
  public static final int PARENTESIS_APERTURA = 47;
  public static final int A_MODULO = 69;
  public static final int MULTIPLICACION = 34;
  public static final int ASIGNACION = 37;
  public static final int CASE = 14;
  public static final int IFX = 63;
  public static final int NEW = 19;
  public static final int STRING = 27;
  public static final int A_DIVISION = 68;
  public static final int AND = 45;
  public static final int CORCHETE_CIERRE = 52;
  public static final int PRIVATE = 4;
  public static final int STATIC = 6;
  public static final int A_RESTA = 66;
  public static final int A_SUMA = 65;
  public static final int MAYOR_IGUAL = 43;
}

