
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 15 14:44:11 CST 2025
//----------------------------------------------------

package act2;

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Oct 15 14:44:11 CST 2025
  */
public class Sintactico extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintactico() {super();}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\133\000\002\002\004\000\002\002\003\000\002\002" +
    "\002\000\002\003\004\000\002\003\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\004\000\002\005\010\000" +
    "\002\005\007\000\002\006\003\000\002\006\002\000\002" +
    "\007\004\000\002\007\003\000\002\010\003\000\002\010" +
    "\004\000\002\011\010\000\002\015\004\000\002\016\005" +
    "\000\002\016\003\000\002\017\003\000\002\017\005\000" +
    "\002\012\003\000\002\012\002\000\002\013\005\000\002" +
    "\013\003\000\002\014\004\000\002\020\003\000\002\020" +
    "\003\000\002\020\003\000\002\020\003\000\002\020\003" +
    "\000\002\020\003\000\002\020\003\000\002\020\003\000" +
    "\002\020\003\000\002\021\005\000\002\021\004\000\002" +
    "\022\004\000\002\022\003\000\002\023\004\000\002\023" +
    "\003\000\002\023\003\000\002\023\003\000\002\023\003" +
    "\000\002\023\003\000\002\023\004\000\002\027\006\000" +
    "\002\027\006\000\002\027\006\000\002\027\006\000\002" +
    "\027\006\000\002\027\006\000\002\027\005\000\002\027" +
    "\005\000\002\027\005\000\002\027\005\000\002\030\007" +
    "\000\002\030\011\000\002\031\007\000\002\031\013\000" +
    "\002\032\003\000\002\032\003\000\002\032\002\000\002" +
    "\033\003\000\002\033\002\000\002\034\003\000\002\034" +
    "\002\000\002\024\003\000\002\024\003\000\002\024\003" +
    "\000\002\024\003\000\002\024\003\000\002\024\003\000" +
    "\002\024\005\000\002\024\005\000\002\024\005\000\002" +
    "\024\005\000\002\024\005\000\002\024\005\000\002\024" +
    "\005\000\002\024\005\000\002\024\005\000\002\024\005" +
    "\000\002\024\005\000\002\024\005\000\002\024\005\000" +
    "\002\024\005\000\002\024\004\000\002\025\003\000\002" +
    "\026\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\242\000\030\002\uffff\004\005\005\006\006\021\007" +
    "\013\010\022\011\007\012\011\013\012\067\016\076\023" +
    "\001\002\000\004\002\244\001\002\000\004\067\uffe6\001" +
    "\002\000\004\067\uffe5\001\002\000\004\067\uffe1\001\002" +
    "\000\030\002\ufffb\004\ufffb\005\ufffb\006\ufffb\007\ufffb\010" +
    "\ufffb\011\ufffb\012\ufffb\013\ufffb\067\ufffb\076\ufffb\001\002" +
    "\000\004\067\uffe0\001\002\000\004\067\uffdf\001\002\000" +
    "\004\067\uffe3\001\002\000\004\056\243\001\002\000\030" +
    "\002\ufffd\004\ufffd\005\ufffd\006\ufffd\007\ufffd\010\ufffd\011" +
    "\ufffd\012\ufffd\013\ufffd\067\ufffd\076\ufffd\001\002\000\004" +
    "\067\uffde\001\002\000\030\002\000\004\005\005\006\006" +
    "\021\007\013\010\022\011\007\012\011\013\012\067\016" +
    "\076\023\001\002\000\004\067\040\001\002\000\004\067" +
    "\uffe4\001\002\000\004\067\uffe2\001\002\000\004\067\025" +
    "\001\002\000\030\002\ufffc\004\ufffc\005\ufffc\006\ufffc\007" +
    "\ufffc\010\ufffc\011\ufffc\012\ufffc\013\ufffc\067\ufffc\076\ufffc" +
    "\001\002\000\004\057\026\001\002\000\026\004\005\005" +
    "\006\006\021\007\013\010\022\011\007\012\011\013\012" +
    "\060\ufff6\067\016\001\002\000\026\004\005\005\006\006" +
    "\021\007\013\010\022\011\007\012\011\013\012\060\ufff7" +
    "\067\016\001\002\000\026\004\ufff3\005\ufff3\006\ufff3\007" +
    "\ufff3\010\ufff3\011\ufff3\012\ufff3\013\ufff3\060\ufff3\067\ufff3" +
    "\001\002\000\004\056\036\001\002\000\004\060\034\001" +
    "\002\000\026\004\ufff4\005\ufff4\006\ufff4\007\ufff4\010\ufff4" +
    "\011\ufff4\012\ufff4\013\ufff4\060\ufff4\067\ufff4\001\002\000" +
    "\032\002\ufff8\004\ufff8\005\ufff8\006\ufff8\007\ufff8\010\ufff8" +
    "\011\ufff8\012\ufff8\013\ufff8\056\035\067\ufff8\076\ufff8\001" +
    "\002\000\030\002\ufff9\004\ufff9\005\ufff9\006\ufff9\007\ufff9" +
    "\010\ufff9\011\ufff9\012\ufff9\013\ufff9\067\ufff9\076\ufff9\001" +
    "\002\000\026\004\ufff2\005\ufff2\006\ufff2\007\ufff2\010\ufff2" +
    "\011\ufff2\012\ufff2\013\ufff2\060\ufff2\067\ufff2\001\002\000" +
    "\026\004\ufff5\005\ufff5\006\ufff5\007\ufff5\010\ufff5\011\ufff5" +
    "\012\ufff5\013\ufff5\060\ufff5\067\ufff5\001\002\000\012\027" +
    "\046\055\uffed\056\uffed\061\115\001\002\000\006\055\043" +
    "\056\ufff0\001\002\000\006\055\uffee\056\uffee\001\002\000" +
    "\004\067\044\001\002\000\010\027\046\055\uffed\056\uffed" +
    "\001\002\000\006\055\uffef\056\uffef\001\002\000\022\054" +
    "\055\061\056\067\054\070\047\071\057\072\052\073\050" +
    "\074\051\001\002\000\042\035\uffbb\036\uffbb\037\uffbb\040" +
    "\uffbb\041\uffbb\044\uffbb\045\uffbb\046\uffbb\047\uffbb\050\uffbb" +
    "\051\uffbb\052\uffbb\053\uffbb\055\uffbb\056\uffbb\062\uffbb\001" +
    "\002\000\042\035\uffbc\036\uffbc\037\uffbc\040\uffbc\041\uffbc" +
    "\044\uffbc\045\uffbc\046\uffbc\047\uffbc\050\uffbc\051\uffbc\052" +
    "\uffbc\053\uffbc\055\uffbc\056\uffbc\062\uffbc\001\002\000\042" +
    "\035\uffbd\036\uffbd\037\uffbd\040\uffbd\041\uffbd\044\uffbd\045" +
    "\uffbd\046\uffbd\047\uffbd\050\uffbd\051\uffbd\052\uffbd\053\uffbd" +
    "\055\uffbd\056\uffbd\062\uffbd\001\002\000\042\035\uffb9\036" +
    "\uffb9\037\uffb9\040\uffb9\041\uffb9\044\uffb9\045\uffb9\046\uffb9" +
    "\047\uffb9\050\uffb9\051\uffb9\052\uffb9\053\uffb9\055\uffb9\056" +
    "\uffb9\062\uffb9\001\002\000\040\035\062\036\074\037\066" +
    "\040\072\041\071\044\070\045\065\046\067\047\063\050" +
    "\064\051\076\052\061\053\075\055\uffec\056\uffec\001\002" +
    "\000\042\035\uffb8\036\uffb8\037\uffb8\040\uffb8\041\uffb8\044" +
    "\uffb8\045\uffb8\046\uffb8\047\uffb8\050\uffb8\051\uffb8\052\uffb8" +
    "\053\uffb8\055\uffb8\056\uffb8\062\uffb8\001\002\000\022\054" +
    "\055\061\056\067\054\070\047\071\057\072\052\073\050" +
    "\074\051\001\002\000\022\054\055\061\056\067\054\070" +
    "\047\071\057\072\052\073\050\074\051\001\002\000\042" +
    "\035\uffba\036\uffba\037\uffba\040\uffba\041\uffba\044\uffba\045" +
    "\uffba\046\uffba\047\uffba\050\uffba\051\uffba\052\uffba\053\uffba" +
    "\055\uffba\056\uffba\062\uffba\001\002\000\036\035\062\036" +
    "\074\037\066\040\072\041\071\044\070\045\065\046\067" +
    "\047\063\050\064\051\076\052\061\053\075\062\073\001" +
    "\002\000\022\054\055\061\056\067\054\070\047\071\057" +
    "\072\052\073\050\074\051\001\002\000\022\054\055\061" +
    "\056\067\054\070\047\071\057\072\052\073\050\074\051" +
    "\001\002\000\022\054\055\061\056\067\054\070\047\071" +
    "\057\072\052\073\050\074\051\001\002\000\022\054\055" +
    "\061\056\067\054\070\047\071\057\072\052\073\050\074" +
    "\051\001\002\000\022\054\055\061\056\067\054\070\047" +
    "\071\057\072\052\073\050\074\051\001\002\000\022\054" +
    "\055\061\056\067\054\070\047\071\057\072\052\073\050" +
    "\074\051\001\002\000\022\054\055\061\056\067\054\070" +
    "\047\071\057\072\052\073\050\074\051\001\002\000\022" +
    "\054\055\061\056\067\054\070\047\071\057\072\052\073" +
    "\050\074\051\001\002\000\022\054\055\061\056\067\054" +
    "\070\047\071\057\072\052\073\050\074\051\001\002\000" +
    "\022\054\055\061\056\067\054\070\047\071\057\072\052" +
    "\073\050\074\051\001\002\000\042\035\uffb7\036\uffb7\037" +
    "\uffb7\040\uffb7\041\uffb7\044\uffb7\045\uffb7\046\uffb7\047\uffb7" +
    "\050\uffb7\051\uffb7\052\uffb7\053\uffb7\055\uffb7\056\uffb7\062" +
    "\uffb7\001\002\000\022\054\055\061\056\067\054\070\047" +
    "\071\057\072\052\073\050\074\051\001\002\000\022\054" +
    "\055\061\056\067\054\070\047\071\057\072\052\073\050" +
    "\074\051\001\002\000\022\054\055\061\056\067\054\070" +
    "\047\071\057\072\052\073\050\074\051\001\002\000\026" +
    "\035\062\036\074\037\066\040\072\041\071\052\uffac\053" +
    "\uffac\055\uffac\056\uffac\062\uffac\001\002\000\042\035\062" +
    "\036\074\037\066\040\072\041\071\044\070\045\065\046" +
    "\067\047\063\050\064\051\076\052\061\053\uffaa\055\uffaa" +
    "\056\uffaa\062\uffaa\001\002\000\042\035\uffb5\036\uffb5\037" +
    "\066\040\072\041\071\044\uffb5\045\uffb5\046\uffb5\047\uffb5" +
    "\050\uffb5\051\uffb5\052\uffb5\053\uffb5\055\uffb5\056\uffb5\062" +
    "\uffb5\001\002\000\042\035\uffb3\036\uffb3\037\uffb3\040\uffb3" +
    "\041\uffb3\044\uffb3\045\uffb3\046\uffb3\047\uffb3\050\uffb3\051" +
    "\uffb3\052\uffb3\053\uffb3\055\uffb3\056\uffb3\062\uffb3\001\002" +
    "\000\042\035\uffb2\036\uffb2\037\uffb2\040\uffb2\041\uffb2\044" +
    "\uffb2\045\uffb2\046\uffb2\047\uffb2\050\uffb2\051\uffb2\052\uffb2" +
    "\053\uffb2\055\uffb2\056\uffb2\062\uffb2\001\002\000\026\035" +
    "\062\036\074\037\066\040\072\041\071\052\uffb1\053\uffb1" +
    "\055\uffb1\056\uffb1\062\uffb1\001\002\000\026\035\062\036" +
    "\074\037\066\040\072\041\071\052\uffaf\053\uffaf\055\uffaf" +
    "\056\uffaf\062\uffaf\001\002\000\042\035\uffb4\036\uffb4\037" +
    "\uffb4\040\uffb4\041\uffb4\044\uffb4\045\uffb4\046\uffb4\047\uffb4" +
    "\050\uffb4\051\uffb4\052\uffb4\053\uffb4\055\uffb4\056\uffb4\062" +
    "\uffb4\001\002\000\026\035\062\036\074\037\066\040\072" +
    "\041\071\052\uffb0\053\uffb0\055\uffb0\056\uffb0\062\uffb0\001" +
    "\002\000\026\035\062\036\074\037\066\040\072\041\071" +
    "\052\uffad\053\uffad\055\uffad\056\uffad\062\uffad\001\002\000" +
    "\026\035\062\036\074\037\066\040\072\041\071\052\uffae" +
    "\053\uffae\055\uffae\056\uffae\062\uffae\001\002\000\042\035" +
    "\uffb6\036\uffb6\037\066\040\072\041\071\044\uffb6\045\uffb6" +
    "\046\uffb6\047\uffb6\050\uffb6\051\uffb6\052\uffb6\053\uffb6\055" +
    "\uffb6\056\uffb6\062\uffb6\001\002\000\042\035\062\036\074" +
    "\037\066\040\072\041\071\044\070\045\065\046\067\047" +
    "\063\050\064\051\076\052\uffab\053\uffab\055\uffab\056\uffab" +
    "\062\uffab\001\002\000\042\035\uffa9\036\uffa9\037\uffa9\040" +
    "\uffa9\041\uffa9\044\uffa9\045\uffa9\046\uffa9\047\uffa9\050\uffa9" +
    "\051\uffa9\052\uffa9\053\uffa9\055\uffa9\056\uffa9\062\uffa9\001" +
    "\002\000\026\004\005\005\006\006\021\007\013\010\022" +
    "\011\007\012\011\013\012\062\uffea\067\016\001\002\000" +
    "\006\055\uffe8\062\uffe8\001\002\000\004\062\125\001\002" +
    "\000\004\067\124\001\002\000\006\055\122\062\uffeb\001" +
    "\002\000\024\004\005\005\006\006\021\007\013\010\022" +
    "\011\007\012\011\013\012\067\016\001\002\000\006\055" +
    "\uffe9\062\uffe9\001\002\000\006\055\uffe7\062\uffe7\001\002" +
    "\000\004\057\127\001\002\000\032\002\ufff1\004\ufff1\005" +
    "\ufff1\006\ufff1\007\ufff1\010\ufff1\011\ufff1\012\ufff1\013\ufff1" +
    "\060\ufff1\067\ufff1\076\ufff1\001\002\000\046\003\145\004" +
    "\005\005\006\006\021\007\013\010\022\011\007\012\011" +
    "\013\012\014\136\017\150\020\133\042\144\043\147\056" +
    "\131\057\127\060\130\067\140\001\002\000\054\002\uffdc" +
    "\003\uffdc\004\uffdc\005\uffdc\006\uffdc\007\uffdc\010\uffdc\011" +
    "\uffdc\012\uffdc\013\uffdc\014\uffdc\015\uffdc\017\uffdc\020\uffdc" +
    "\042\uffdc\043\uffdc\056\uffdc\057\uffdc\060\uffdc\067\uffdc\076" +
    "\uffdc\001\002\000\050\003\uffd4\004\uffd4\005\uffd4\006\uffd4" +
    "\007\uffd4\010\uffd4\011\uffd4\012\uffd4\013\uffd4\014\uffd4\015" +
    "\uffd4\017\uffd4\020\uffd4\042\uffd4\043\uffd4\056\uffd4\057\uffd4" +
    "\060\uffd4\067\uffd4\001\002\000\004\056\241\001\002\000" +
    "\004\061\235\001\002\000\046\003\145\004\005\005\006" +
    "\006\021\007\013\010\022\011\007\012\011\013\012\014" +
    "\136\017\150\020\133\042\144\043\147\056\131\057\127" +
    "\060\233\067\140\001\002\000\050\003\uffd5\004\uffd5\005" +
    "\uffd5\006\uffd5\007\uffd5\010\uffd5\011\uffd5\012\uffd5\013\uffd5" +
    "\014\uffd5\015\uffd5\017\uffd5\020\uffd5\042\uffd5\043\uffd5\056" +
    "\uffd5\057\uffd5\060\uffd5\067\uffd5\001\002\000\004\061\225" +
    "\001\002\000\004\067\044\001\002\000\024\027\uffa8\030" +
    "\uffa8\031\uffa8\032\uffa8\033\uffa8\034\uffa8\042\uffa8\043\uffa8" +
    "\067\uffde\001\002\000\050\003\uffd6\004\uffd6\005\uffd6\006" +
    "\uffd6\007\uffd6\010\uffd6\011\uffd6\012\uffd6\013\uffd6\014\uffd6" +
    "\015\uffd6\017\uffd6\020\uffd6\042\uffd6\043\uffd6\056\uffd6\057" +
    "\uffd6\060\uffd6\067\uffd6\001\002\000\046\003\uffda\004\uffda" +
    "\005\uffda\006\uffda\007\uffda\010\uffda\011\uffda\012\uffda\013" +
    "\uffda\014\uffda\017\uffda\020\uffda\042\uffda\043\uffda\056\uffda" +
    "\057\uffda\060\uffda\067\uffda\001\002\000\050\003\uffd7\004" +
    "\uffd7\005\uffd7\006\uffd7\007\uffd7\010\uffd7\011\uffd7\012\uffd7" +
    "\013\uffd7\014\uffd7\015\uffd7\017\uffd7\020\uffd7\042\uffd7\043" +
    "\uffd7\056\uffd7\057\uffd7\060\uffd7\067\uffd7\001\002\000\004" +
    "\067\214\001\002\000\004\056\222\001\002\000\050\003" +
    "\uffd8\004\uffd8\005\uffd8\006\uffd8\007\uffd8\010\uffd8\011\uffd8" +
    "\012\uffd8\013\uffd8\014\uffd8\015\uffd8\017\uffd8\020\uffd8\042" +
    "\uffd8\043\uffd8\056\uffd8\057\uffd8\060\uffd8\067\uffd8\001\002" +
    "\000\004\067\214\001\002\000\004\061\200\001\002\000" +
    "\022\027\153\030\156\031\155\032\160\033\154\034\157" +
    "\042\161\043\152\001\002\000\004\056\177\001\002\000" +
    "\022\054\055\061\056\067\054\070\047\071\057\072\052" +
    "\073\050\074\051\001\002\000\022\054\055\061\056\067" +
    "\054\070\047\071\057\072\052\073\050\074\051\001\002" +
    "\000\022\054\055\061\056\067\054\070\047\071\057\072" +
    "\052\073\050\074\051\001\002\000\022\054\055\061\056" +
    "\067\054\070\047\071\057\072\052\073\050\074\051\001" +
    "\002\000\022\054\055\061\056\067\054\070\047\071\057" +
    "\072\052\073\050\074\051\001\002\000\022\054\055\061" +
    "\056\067\054\070\047\071\057\072\052\073\050\074\051" +
    "\001\002\000\004\056\162\001\002\000\050\003\uffcc\004" +
    "\uffcc\005\uffcc\006\uffcc\007\uffcc\010\uffcc\011\uffcc\012\uffcc" +
    "\013\uffcc\014\uffcc\015\uffcc\017\uffcc\020\uffcc\042\uffcc\043" +
    "\uffcc\056\uffcc\057\uffcc\060\uffcc\067\uffcc\001\002\000\036" +
    "\035\062\036\074\037\066\040\072\041\071\044\070\045" +
    "\065\046\067\047\063\050\064\051\076\052\061\053\075" +
    "\056\164\001\002\000\050\003\uffcd\004\uffcd\005\uffcd\006" +
    "\uffcd\007\uffcd\010\uffcd\011\uffcd\012\uffcd\013\uffcd\014\uffcd" +
    "\015\uffcd\017\uffcd\020\uffcd\042\uffcd\043\uffcd\056\uffcd\057" +
    "\uffcd\060\uffcd\067\uffcd\001\002\000\036\035\062\036\074" +
    "\037\066\040\072\041\071\044\070\045\065\046\067\047" +
    "\063\050\064\051\076\052\061\053\075\056\166\001\002" +
    "\000\050\003\uffce\004\uffce\005\uffce\006\uffce\007\uffce\010" +
    "\uffce\011\uffce\012\uffce\013\uffce\014\uffce\015\uffce\017\uffce" +
    "\020\uffce\042\uffce\043\uffce\056\uffce\057\uffce\060\uffce\067" +
    "\uffce\001\002\000\036\035\062\036\074\037\066\040\072" +
    "\041\071\044\070\045\065\046\067\047\063\050\064\051" +
    "\076\052\061\053\075\056\170\001\002\000\050\003\uffd1" +
    "\004\uffd1\005\uffd1\006\uffd1\007\uffd1\010\uffd1\011\uffd1\012" +
    "\uffd1\013\uffd1\014\uffd1\015\uffd1\017\uffd1\020\uffd1\042\uffd1" +
    "\043\uffd1\056\uffd1\057\uffd1\060\uffd1\067\uffd1\001\002\000" +
    "\036\035\062\036\074\037\066\040\072\041\071\044\070" +
    "\045\065\046\067\047\063\050\064\051\076\052\061\053" +
    "\075\056\172\001\002\000\050\003\uffd0\004\uffd0\005\uffd0" +
    "\006\uffd0\007\uffd0\010\uffd0\011\uffd0\012\uffd0\013\uffd0\014" +
    "\uffd0\015\uffd0\017\uffd0\020\uffd0\042\uffd0\043\uffd0\056\uffd0" +
    "\057\uffd0\060\uffd0\067\uffd0\001\002\000\036\035\062\036" +
    "\074\037\066\040\072\041\071\044\070\045\065\046\067" +
    "\047\063\050\064\051\076\052\061\053\075\056\174\001" +
    "\002\000\050\003\uffcf\004\uffcf\005\uffcf\006\uffcf\007\uffcf" +
    "\010\uffcf\011\uffcf\012\uffcf\013\uffcf\014\uffcf\015\uffcf\017" +
    "\uffcf\020\uffcf\042\uffcf\043\uffcf\056\uffcf\057\uffcf\060\uffcf" +
    "\067\uffcf\001\002\000\036\035\062\036\074\037\066\040" +
    "\072\041\071\044\070\045\065\046\067\047\063\050\064" +
    "\051\076\052\061\053\075\056\176\001\002\000\050\003" +
    "\uffd2\004\uffd2\005\uffd2\006\uffd2\007\uffd2\010\uffd2\011\uffd2" +
    "\012\uffd2\013\uffd2\014\uffd2\015\uffd2\017\uffd2\020\uffd2\042" +
    "\uffd2\043\uffd2\056\uffd2\057\uffd2\060\uffd2\067\uffd2\001\002" +
    "\000\050\003\uffcb\004\uffcb\005\uffcb\006\uffcb\007\uffcb\010" +
    "\uffcb\011\uffcb\012\uffcb\013\uffcb\014\uffcb\015\uffcb\017\uffcb" +
    "\020\uffcb\042\uffcb\043\uffcb\056\uffcb\057\uffcb\060\uffcb\067" +
    "\uffcb\001\002\000\026\004\005\005\006\006\021\007\013" +
    "\010\022\011\007\012\011\013\012\056\uffc2\067\140\001" +
    "\002\000\004\056\uffc4\001\002\000\004\056\207\001\002" +
    "\000\004\056\uffc3\001\002\000\004\027\205\001\002\000" +
    "\022\054\055\061\056\067\054\070\047\071\057\072\052" +
    "\073\050\074\051\001\002\000\040\035\062\036\074\037" +
    "\066\040\072\041\071\044\070\045\065\046\067\047\063" +
    "\050\064\051\076\052\061\053\075\056\uffa7\062\uffa7\001" +
    "\002\000\024\054\055\056\uffc0\061\056\067\054\070\047" +
    "\071\057\072\052\073\050\074\051\001\002\000\004\056" +
    "\212\001\002\000\036\035\062\036\074\037\066\040\072" +
    "\041\071\044\070\045\065\046\067\047\063\050\064\051" +
    "\076\052\061\053\075\056\uffc1\001\002\000\006\062\uffbe" +
    "\067\214\001\002\000\004\062\216\001\002\000\006\027" +
    "\uffa8\056\uffa8\001\002\000\004\062\uffbf\001\002\000\044" +
    "\003\145\004\005\005\006\006\021\007\013\010\022\011" +
    "\007\012\011\013\012\014\136\017\150\020\133\042\144" +
    "\043\147\056\131\057\127\067\140\001\002\000\050\003" +
    "\uffc5\004\uffc5\005\uffc5\006\uffc5\007\uffc5\010\uffc5\011\uffc5" +
    "\012\uffc5\013\uffc5\014\uffc5\015\uffc5\017\uffc5\020\uffc5\042" +
    "\uffc5\043\uffc5\056\uffc5\057\uffc5\060\uffc5\067\uffc5\001\002" +
    "\000\004\056\221\001\002\000\050\003\uffc9\004\uffc9\005" +
    "\uffc9\006\uffc9\007\uffc9\010\uffc9\011\uffc9\012\uffc9\013\uffc9" +
    "\014\uffc9\015\uffc9\017\uffc9\020\uffc9\042\uffc9\043\uffc9\056" +
    "\uffc9\057\uffc9\060\uffc9\067\uffc9\001\002\000\050\003\uffd3" +
    "\004\uffd3\005\uffd3\006\uffd3\007\uffd3\010\uffd3\011\uffd3\012" +
    "\uffd3\013\uffd3\014\uffd3\015\uffd3\017\uffd3\020\uffd3\042\uffd3" +
    "\043\uffd3\056\uffd3\057\uffd3\060\uffd3\067\uffd3\001\002\000" +
    "\004\056\224\001\002\000\050\003\uffca\004\uffca\005\uffca" +
    "\006\uffca\007\uffca\010\uffca\011\uffca\012\uffca\013\uffca\014" +
    "\uffca\015\uffca\017\uffca\020\uffca\042\uffca\043\uffca\056\uffca" +
    "\057\uffca\060\uffca\067\uffca\001\002\000\022\054\055\061" +
    "\056\067\054\070\047\071\057\072\052\073\050\074\051" +
    "\001\002\000\036\035\062\036\074\037\066\040\072\041" +
    "\071\044\070\045\065\046\067\047\063\050\064\051\076" +
    "\052\061\053\075\062\227\001\002\000\044\003\145\004" +
    "\005\005\006\006\021\007\013\010\022\011\007\012\011" +
    "\013\012\014\136\017\150\020\133\042\144\043\147\056" +
    "\131\057\127\067\140\001\002\000\050\003\uffc8\004\uffc8" +
    "\005\uffc8\006\uffc8\007\uffc8\010\uffc8\011\uffc8\012\uffc8\013" +
    "\uffc8\014\uffc8\015\uffc8\017\uffc8\020\uffc8\042\uffc8\043\uffc8" +
    "\056\uffc8\057\uffc8\060\uffc8\067\uffc8\001\002\000\044\003" +
    "\145\004\005\005\006\006\021\007\013\010\022\011\007" +
    "\012\011\013\012\014\136\017\150\020\133\042\144\043" +
    "\147\056\131\057\127\067\140\001\002\000\050\003\uffc7" +
    "\004\uffc7\005\uffc7\006\uffc7\007\uffc7\010\uffc7\011\uffc7\012" +
    "\uffc7\013\uffc7\014\uffc7\015\uffc7\017\uffc7\020\uffc7\042\uffc7" +
    "\043\uffc7\056\uffc7\057\uffc7\060\uffc7\067\uffc7\001\002\000" +
    "\054\002\uffdd\003\uffdd\004\uffdd\005\uffdd\006\uffdd\007\uffdd" +
    "\010\uffdd\011\uffdd\012\uffdd\013\uffdd\014\uffdd\015\uffdd\017" +
    "\uffdd\020\uffdd\042\uffdd\043\uffdd\056\uffdd\057\uffdd\060\uffdd" +
    "\067\uffdd\076\uffdd\001\002\000\046\003\uffdb\004\uffdb\005" +
    "\uffdb\006\uffdb\007\uffdb\010\uffdb\011\uffdb\012\uffdb\013\uffdb" +
    "\014\uffdb\017\uffdb\020\uffdb\042\uffdb\043\uffdb\056\uffdb\057" +
    "\uffdb\060\uffdb\067\uffdb\001\002\000\022\054\055\061\056" +
    "\067\054\070\047\071\057\072\052\073\050\074\051\001" +
    "\002\000\036\035\062\036\074\037\066\040\072\041\071" +
    "\044\070\045\065\046\067\047\063\050\064\051\076\052" +
    "\061\053\075\062\237\001\002\000\044\003\145\004\005" +
    "\005\006\006\021\007\013\010\022\011\007\012\011\013" +
    "\012\014\136\017\150\020\133\042\144\043\147\056\131" +
    "\057\127\067\140\001\002\000\050\003\uffc6\004\uffc6\005" +
    "\uffc6\006\uffc6\007\uffc6\010\uffc6\011\uffc6\012\uffc6\013\uffc6" +
    "\014\uffc6\015\uffc6\017\uffc6\020\uffc6\042\uffc6\043\uffc6\056" +
    "\uffc6\057\uffc6\060\uffc6\067\uffc6\001\002\000\050\003\uffd9" +
    "\004\uffd9\005\uffd9\006\uffd9\007\uffd9\010\uffd9\011\uffd9\012" +
    "\uffd9\013\uffd9\014\uffd9\015\uffd9\017\uffd9\020\uffd9\042\uffd9" +
    "\043\uffd9\056\uffd9\057\uffd9\060\uffd9\067\uffd9\001\002\000" +
    "\030\002\ufffe\004\ufffe\005\ufffe\006\ufffe\007\ufffe\010\ufffe" +
    "\011\ufffe\012\ufffe\013\ufffe\067\ufffe\076\ufffe\001\002\000" +
    "\030\002\ufffa\004\ufffa\005\ufffa\006\ufffa\007\ufffa\010\ufffa" +
    "\011\ufffa\012\ufffa\013\ufffa\067\ufffa\076\ufffa\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\242\000\020\002\003\003\016\004\014\005\023\011" +
    "\007\015\013\020\017\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\004\241\005\023\011\007\015\013\020\017\001\001" +
    "\000\006\016\040\017\041\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\016\006\031\007\026\010\032\011\027\015" +
    "\030\020\017\001\001\000\012\010\036\011\027\015\030" +
    "\020\017\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\017\044" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\024" +
    "\052\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\024\113\001\001\000\004\024\057\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\024\112\001" +
    "\001\000\004\024\111\001\001\000\004\024\110\001\001" +
    "\000\004\024\107\001\001\000\004\024\106\001\001\000" +
    "\004\024\105\001\001\000\004\024\104\001\001\000\004" +
    "\024\103\001\001\000\004\024\102\001\001\000\004\024" +
    "\101\001\001\000\002\001\001\000\004\024\100\001\001" +
    "\000\004\024\077\001\001\000\004\024\076\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\012\116\013\120\014\115\020\117" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\014\122\020\117\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\021\125\001" +
    "\001\000\002\001\001\000\024\015\131\020\136\021\134" +
    "\022\133\023\141\025\150\027\145\030\142\031\140\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\022\015\131\020\136\021\134\023" +
    "\233\025\150\027\145\030\142\031\140\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\016\040\017\041\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\025\222\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\025\217\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\024" +
    "\174\001\001\000\004\024\172\001\001\000\004\024\170" +
    "\001\001\000\004\024\166\001\001\000\004\024\164\001" +
    "\001\000\004\024\162\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\015\200\020\136\025\203\026\202\032" +
    "\201\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\024\205\001\001\000" +
    "\002\001\001\000\006\024\210\033\207\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\025\203\026\214\034" +
    "\212\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\015\131\020\136\021\134\023\216\025" +
    "\150\027\145\030\142\031\140\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\024\225\001\001" +
    "\000\002\001\001\000\022\015\131\020\136\021\134\023" +
    "\227\025\150\027\145\030\142\031\140\001\001\000\002" +
    "\001\001\000\022\015\131\020\136\021\134\023\231\025" +
    "\150\027\145\030\142\031\140\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\024\235\001" +
    "\001\000\002\001\001\000\022\015\131\020\136\021\134" +
    "\023\237\025\150\027\145\030\142\031\140\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    
    protected Symbol lastErrorToken;
    public void report_fatal_error(String mensaje, Object informacion) { report_error(mensaje, informacion); }
    public void syntax_error(Symbol token_actual) {
        this.lastErrorToken = token_actual;
        String mensajeError = "Error de sintaxis. ";
        if (token_actual != null && token_actual.value != null) {
            mensajeError += "Token inesperado: '" + token_actual.value + "'.";
        }
        System.err.println(mensajeError + " En la línea: " + (token_actual.left + 1) + ", Columna: " + (token_actual.right + 1));
    }
    public void report_error(String mensaje, Object informacion) {
        if (informacion instanceof Symbol) {
            Symbol s = ((Symbol) informacion);
            if (s.left >= 0 && s.right >= 0) {
                System.err.println(mensaje + " Cerca de la línea: " + (s.left + 1) + ", Columna: " + (s.right + 1));
                return;
            }
        }
        System.err.println(mensaje);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintactico$actions {
  private final Sintactico parser;

  /** Constructor */
  CUP$Sintactico$actions(Sintactico parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // asignacion_expr ::= lvalue ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("asignacion_expr",20, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // lvalue ::= ID 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lvalue",19, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // expresion ::= NOT expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // expresion ::= expresion OR expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // expresion ::= expresion AND expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // expresion ::= expresion MENOR_IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // expresion ::= expresion MAYOR_IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // expresion ::= expresion MENOR expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // expresion ::= expresion MAYOR expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // expresion ::= expresion DIFERENCIA expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // expresion ::= expresion IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // expresion ::= expresion MODULO expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // expresion ::= expresion DIVISION expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // expresion ::= expresion MULTIPLICACION expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // expresion ::= expresion RESTA expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // expresion ::= expresion SUMA expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // expresion ::= PARENTESIS_APERTURA expresion PARENTESIS_CIERRE 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expresion ::= ID 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expresion ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expresion ::= CARACTER 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expresion ::= CADENA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expresion ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expresion ::= ENTERO 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // for_actualizacion ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_actualizacion",26, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // for_actualizacion ::= asignacion_expr 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_actualizacion",26, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // for_condicion ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_condicion",25, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // for_condicion ::= expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_condicion",25, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // for_init ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_init",24, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // for_init ::= asignacion_expr 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_init",24, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // for_init ::= dec_variable_lista 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_init",24, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // sentencia_iterativa ::= FOR PARENTESIS_APERTURA for_init PUNTOYCOMA for_condicion PUNTOYCOMA for_actualizacion PARENTESIS_CIERRE sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_iterativa",23, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // sentencia_iterativa ::= WHILE PARENTESIS_APERTURA expresion PARENTESIS_CIERRE sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_iterativa",23, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // sentencia_condicional ::= IF PARENTESIS_APERTURA expresion PARENTESIS_CIERRE sentencia ELSE sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_condicional",22, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-6)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // sentencia_condicional ::= IF PARENTESIS_APERTURA expresion PARENTESIS_CIERRE sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_condicional",22, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // sentencia_asignacion ::= DECREMENTO lvalue PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // sentencia_asignacion ::= INCREMENTO lvalue PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // sentencia_asignacion ::= lvalue DECREMENTO PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // sentencia_asignacion ::= lvalue INCREMENTO PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // sentencia_asignacion ::= lvalue A_MODULO expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // sentencia_asignacion ::= lvalue A_DIVISION expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // sentencia_asignacion ::= lvalue A_MULTIPLICACION expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // sentencia_asignacion ::= lvalue A_RESTA expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // sentencia_asignacion ::= lvalue A_SUMA expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // sentencia_asignacion ::= lvalue ASIGNACION expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // sentencia ::= error PUNTOYCOMA 
            {
              Object RESULT =null;
		 parser.report_error("Error de sintaxis en la sentencia.", null); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // sentencia ::= PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // sentencia ::= bloque 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // sentencia ::= sentencia_iterativa 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // sentencia ::= sentencia_condicional 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // sentencia ::= sentencia_asignacion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // sentencia ::= dec_variable_lista PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // lista_sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_sentencias",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_sentencias",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // bloque ::= LLAVE_APERTURA LLAVE_CIERRE 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("bloque",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // bloque ::= LLAVE_APERTURA lista_sentencias LLAVE_CIERRE 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("bloque",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // tipo_dato ::= ID 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // tipo_dato ::= STRING 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // tipo_dato ::= VOID 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // tipo_dato ::= BOOL 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // tipo_dato ::= CHAR 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // tipo_dato ::= DOUBLE 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // tipo_dato ::= FLOAT 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // tipo_dato ::= LONG 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // tipo_dato ::= INT 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // parametro ::= tipo_dato ID 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("parametro",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // lista_parametros ::= parametro 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_parametros",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // lista_parametros ::= lista_parametros COMA parametro 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_parametros",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // lista_parametros_opcional ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_parametros_opcional",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // lista_parametros_opcional ::= lista_parametros 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_parametros_opcional",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // id_con_asignacion_opcional ::= ID ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("id_con_asignacion_opcional",13, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // id_con_asignacion_opcional ::= ID 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("id_con_asignacion_opcional",13, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // lista_ids_con_asignacion ::= id_con_asignacion_opcional 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_ids_con_asignacion",12, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // lista_ids_con_asignacion ::= lista_ids_con_asignacion COMA id_con_asignacion_opcional 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_ids_con_asignacion",12, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // dec_variable_lista ::= tipo_dato lista_ids_con_asignacion 
            {
              Object RESULT =null;
		 System.out.println("-> Se reconoció una declaración de variable(s)."); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_variable_lista",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // dec_funcion ::= tipo_dato ID PARENTESIS_APERTURA lista_parametros_opcional PARENTESIS_CIERRE bloque 
            {
              Object RESULT =null;
		 System.out.println("-> Se reconoció una función/método."); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_funcion",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // miembro ::= dec_variable_lista PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("miembro",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // miembro ::= dec_funcion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("miembro",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // lista_miembros ::= miembro 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_miembros",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_miembros ::= lista_miembros miembro 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_miembros",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // cuerpo_clase ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("cuerpo_clase",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // cuerpo_clase ::= lista_miembros 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("cuerpo_clase",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // dec_clase ::= CLASS ID LLAVE_APERTURA cuerpo_clase LLAVE_CIERRE 
            {
              Object RESULT =null;
		 System.out.println("-> Se reconoció una clase."); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_clase",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // dec_clase ::= CLASS ID LLAVE_APERTURA cuerpo_clase LLAVE_CIERRE PUNTOYCOMA 
            {
              Object RESULT =null;
		 System.out.println("-> Se reconoció una clase."); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_clase",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declaracion ::= dec_variable_lista PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("declaracion",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declaracion ::= dec_funcion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("declaracion",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declaracion ::= dec_clase 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("declaracion",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_declaraciones ::= declaracion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_declaraciones",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_declaraciones ::= lista_declaraciones declaracion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_declaraciones",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= lista_declaraciones 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico$parser.done_parsing();
          return CUP$Sintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

