
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 12 20:39:50 CST 2025
//----------------------------------------------------

package act2;

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Oct 12 20:39:50 CST 2025
  */
public class Sintactico extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintactico() {super();}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\112\000\002\002\004\000\002\002\003\000\002\002" +
    "\002\000\002\006\004\000\002\006\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\007\003\000" +
    "\002\007\003\000\002\007\003\000\002\007\004\000\002" +
    "\010\005\000\002\010\004\000\002\003\007\000\002\003" +
    "\005\000\002\003\005\000\002\003\005\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\004\003\000\002\004\003\000\002" +
    "\004\003\000\002\011\006\000\002\011\006\000\002\011" +
    "\006\000\002\011\006\000\002\011\006\000\002\011\006" +
    "\000\002\011\005\000\002\011\005\000\002\011\005\000" +
    "\002\011\005\000\002\012\007\000\002\012\011\000\002" +
    "\012\006\000\002\012\006\000\002\013\007\000\002\013" +
    "\013\000\002\013\006\000\002\013\007\000\002\014\006" +
    "\000\002\014\003\000\002\014\002\000\002\015\003\000" +
    "\002\015\002\000\002\016\003\000\002\016\002\000\002" +
    "\005\003\000\002\005\003\000\002\005\003\000\002\005" +
    "\003\000\002\005\003\000\002\005\003\000\002\005\005" +
    "\000\002\005\005\000\002\005\005\000\002\005\005\000" +
    "\002\005\005\000\002\005\005\000\002\005\005\000\002" +
    "\005\005\000\002\005\005\000\002\005\005\000\002\005" +
    "\005\000\002\005\005\000\002\005\005\000\002\005\005" +
    "\000\002\005\004\000\002\017\003\000\002\020\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\215\000\046\002\uffff\003\025\004\006\005\004\006" +
    "\022\007\036\010\007\011\027\012\035\013\020\014\013" +
    "\017\032\020\010\042\024\043\030\056\005\057\031\071" +
    "\014\001\002\000\004\071\uffee\001\002\000\052\002\ufff7" +
    "\003\ufff7\004\ufff7\005\ufff7\006\ufff7\007\ufff7\010\ufff7\011" +
    "\ufff7\012\ufff7\013\ufff7\014\ufff7\015\ufff7\017\ufff7\020\ufff7" +
    "\042\ufff7\043\ufff7\056\ufff7\057\ufff7\060\ufff7\071\ufff7\001" +
    "\002\000\004\071\uffef\001\002\000\004\071\uffeb\001\002" +
    "\000\004\061\213\001\002\000\046\002\000\003\025\004" +
    "\006\005\004\006\022\007\036\010\007\011\027\012\035" +
    "\013\020\014\013\017\032\020\010\042\024\043\030\056" +
    "\005\057\031\071\014\001\002\000\052\002\ufff8\003\ufff8" +
    "\004\ufff8\005\ufff8\006\ufff8\007\ufff8\010\ufff8\011\ufff8\012" +
    "\ufff8\013\ufff8\014\ufff8\015\ufff8\017\ufff8\020\ufff8\042\ufff8" +
    "\043\ufff8\056\ufff8\057\ufff8\060\ufff8\071\ufff8\001\002\000" +
    "\006\003\202\061\201\001\002\000\024\027\uffb9\030\uffb9" +
    "\031\uffb9\032\uffb9\033\uffb9\034\uffb9\042\uffb9\043\uffb9\056" +
    "\uffb9\001\002\000\004\071\173\001\002\000\004\002\172" +
    "\001\002\000\052\002\ufff9\003\ufff9\004\ufff9\005\ufff9\006" +
    "\ufff9\007\ufff9\010\ufff9\011\ufff9\012\ufff9\013\ufff9\014\ufff9" +
    "\015\ufff9\017\ufff9\020\ufff9\042\ufff9\043\ufff9\056\ufff9\057" +
    "\ufff9\060\ufff9\071\ufff9\001\002\000\004\071\uffe8\001\002" +
    "\000\050\002\ufffd\003\ufffd\004\ufffd\005\ufffd\006\ufffd\007" +
    "\ufffd\010\ufffd\011\ufffd\012\ufffd\013\ufffd\014\ufffd\017\ufffd" +
    "\020\ufffd\042\ufffd\043\ufffd\056\ufffd\057\ufffd\060\ufffd\071" +
    "\ufffd\001\002\000\004\071\uffed\001\002\000\052\002\ufffa" +
    "\003\ufffa\004\ufffa\005\ufffa\006\ufffa\007\ufffa\010\ufffa\011" +
    "\ufffa\012\ufffa\013\ufffa\014\ufffa\015\ufffa\017\ufffa\020\ufffa" +
    "\042\ufffa\043\ufffa\056\ufffa\057\ufffa\060\ufffa\071\ufffa\001" +
    "\002\000\004\071\014\001\002\000\006\056\166\071\165" +
    "\001\002\000\052\002\ufffb\003\ufffb\004\ufffb\005\ufffb\006" +
    "\ufffb\007\ufffb\010\ufffb\011\ufffb\012\ufffb\013\ufffb\014\ufffb" +
    "\015\ufffb\017\ufffb\020\ufffb\042\ufffb\043\ufffb\056\ufffb\057" +
    "\ufffb\060\ufffb\071\ufffb\001\002\000\004\071\uffea\001\002" +
    "\000\004\071\014\001\002\000\046\003\025\004\006\005" +
    "\004\006\022\007\036\010\007\011\027\012\035\013\020" +
    "\014\013\017\032\020\010\042\024\043\030\056\005\057" +
    "\031\060\157\071\014\001\002\000\004\061\132\001\002" +
    "\000\022\027\040\030\043\031\042\032\045\033\041\034" +
    "\044\042\046\043\037\001\002\000\052\002\ufffc\003\ufffc" +
    "\004\ufffc\005\ufffc\006\ufffc\007\ufffc\010\ufffc\011\ufffc\012" +
    "\ufffc\013\ufffc\014\ufffc\015\ufffc\017\ufffc\020\ufffc\042\ufffc" +
    "\043\ufffc\056\ufffc\057\ufffc\060\ufffc\071\ufffc\001\002\000" +
    "\004\071\uffe9\001\002\000\004\071\uffec\001\002\000\004" +
    "\056\131\001\002\000\022\054\056\061\060\071\055\072" +
    "\050\073\057\074\053\075\051\076\052\001\002\000\022" +
    "\054\056\061\060\071\055\072\050\073\057\074\053\075" +
    "\051\076\052\001\002\000\022\054\056\061\060\071\055" +
    "\072\050\073\057\074\053\075\051\076\052\001\002\000" +
    "\022\054\056\061\060\071\055\072\050\073\057\074\053" +
    "\075\051\076\052\001\002\000\022\054\056\061\060\071" +
    "\055\072\050\073\057\074\053\075\051\076\052\001\002" +
    "\000\022\054\056\061\060\071\055\072\050\073\057\074" +
    "\053\075\051\076\052\001\002\000\004\056\047\001\002" +
    "\000\052\002\uffe1\003\uffe1\004\uffe1\005\uffe1\006\uffe1\007" +
    "\uffe1\010\uffe1\011\uffe1\012\uffe1\013\uffe1\014\uffe1\015\uffe1" +
    "\017\uffe1\020\uffe1\042\uffe1\043\uffe1\056\uffe1\057\uffe1\060" +
    "\uffe1\071\uffe1\001\002\000\042\003\uffcc\035\uffcc\036\uffcc" +
    "\037\uffcc\040\uffcc\041\uffcc\044\uffcc\045\uffcc\046\uffcc\047" +
    "\uffcc\050\uffcc\051\uffcc\052\uffcc\053\uffcc\056\uffcc\062\uffcc" +
    "\001\002\000\042\003\uffcd\035\uffcd\036\uffcd\037\uffcd\040" +
    "\uffcd\041\uffcd\044\uffcd\045\uffcd\046\uffcd\047\uffcd\050\uffcd" +
    "\051\uffcd\052\uffcd\053\uffcd\056\uffcd\062\uffcd\001\002\000" +
    "\042\003\uffce\035\uffce\036\uffce\037\uffce\040\uffce\041\uffce" +
    "\044\uffce\045\uffce\046\uffce\047\uffce\050\uffce\051\uffce\052" +
    "\uffce\053\uffce\056\uffce\062\uffce\001\002\000\042\003\uffca" +
    "\035\uffca\036\uffca\037\uffca\040\uffca\041\uffca\044\uffca\045" +
    "\uffca\046\uffca\047\uffca\050\uffca\051\uffca\052\uffca\053\uffca" +
    "\056\uffca\062\uffca\001\002\000\036\035\064\036\075\037" +
    "\067\040\073\041\072\044\071\045\066\046\070\047\063" +
    "\050\065\051\077\052\062\053\076\056\116\001\002\000" +
    "\042\003\uffc9\035\uffc9\036\uffc9\037\uffc9\040\uffc9\041\uffc9" +
    "\044\uffc9\045\uffc9\046\uffc9\047\uffc9\050\uffc9\051\uffc9\052" +
    "\uffc9\053\uffc9\056\uffc9\062\uffc9\001\002\000\022\054\056" +
    "\061\060\071\055\072\050\073\057\074\053\075\051\076" +
    "\052\001\002\000\042\003\uffcb\035\uffcb\036\uffcb\037\uffcb" +
    "\040\uffcb\041\uffcb\044\uffcb\045\uffcb\046\uffcb\047\uffcb\050" +
    "\uffcb\051\uffcb\052\uffcb\053\uffcb\056\uffcb\062\uffcb\001\002" +
    "\000\022\054\056\061\060\071\055\072\050\073\057\074" +
    "\053\075\051\076\052\001\002\000\036\035\064\036\075" +
    "\037\067\040\073\041\072\044\071\045\066\046\070\047" +
    "\063\050\065\051\077\052\062\053\076\062\074\001\002" +
    "\000\022\054\056\061\060\071\055\072\050\073\057\074" +
    "\053\075\051\076\052\001\002\000\022\054\056\061\060" +
    "\071\055\072\050\073\057\074\053\075\051\076\052\001" +
    "\002\000\022\054\056\061\060\071\055\072\050\073\057" +
    "\074\053\075\051\076\052\001\002\000\022\054\056\061" +
    "\060\071\055\072\050\073\057\074\053\075\051\076\052" +
    "\001\002\000\022\054\056\061\060\071\055\072\050\073" +
    "\057\074\053\075\051\076\052\001\002\000\022\054\056" +
    "\061\060\071\055\072\050\073\057\074\053\075\051\076" +
    "\052\001\002\000\022\054\056\061\060\071\055\072\050" +
    "\073\057\074\053\075\051\076\052\001\002\000\022\054" +
    "\056\061\060\071\055\072\050\073\057\074\053\075\051" +
    "\076\052\001\002\000\022\054\056\061\060\071\055\072" +
    "\050\073\057\074\053\075\051\076\052\001\002\000\022" +
    "\054\056\061\060\071\055\072\050\073\057\074\053\075" +
    "\051\076\052\001\002\000\042\003\uffc8\035\uffc8\036\uffc8" +
    "\037\uffc8\040\uffc8\041\uffc8\044\uffc8\045\uffc8\046\uffc8\047" +
    "\uffc8\050\uffc8\051\uffc8\052\uffc8\053\uffc8\056\uffc8\062\uffc8" +
    "\001\002\000\022\054\056\061\060\071\055\072\050\073" +
    "\057\074\053\075\051\076\052\001\002\000\022\054\056" +
    "\061\060\071\055\072\050\073\057\074\053\075\051\076" +
    "\052\001\002\000\022\054\056\061\060\071\055\072\050" +
    "\073\057\074\053\075\051\076\052\001\002\000\026\003" +
    "\uffbd\035\064\036\075\037\067\040\073\041\072\052\uffbd" +
    "\053\uffbd\056\uffbd\062\uffbd\001\002\000\042\003\uffbb\035" +
    "\064\036\075\037\067\040\073\041\072\044\071\045\066" +
    "\046\070\047\063\050\065\051\077\052\062\053\uffbb\056" +
    "\uffbb\062\uffbb\001\002\000\042\003\uffc6\035\uffc6\036\uffc6" +
    "\037\067\040\073\041\072\044\uffc6\045\uffc6\046\uffc6\047" +
    "\uffc6\050\uffc6\051\uffc6\052\uffc6\053\uffc6\056\uffc6\062\uffc6" +
    "\001\002\000\042\003\uffc4\035\uffc4\036\uffc4\037\uffc4\040" +
    "\uffc4\041\uffc4\044\uffc4\045\uffc4\046\uffc4\047\uffc4\050\uffc4" +
    "\051\uffc4\052\uffc4\053\uffc4\056\uffc4\062\uffc4\001\002\000" +
    "\042\003\uffc3\035\uffc3\036\uffc3\037\uffc3\040\uffc3\041\uffc3" +
    "\044\uffc3\045\uffc3\046\uffc3\047\uffc3\050\uffc3\051\uffc3\052" +
    "\uffc3\053\uffc3\056\uffc3\062\uffc3\001\002\000\026\003\uffc2" +
    "\035\064\036\075\037\067\040\073\041\072\052\uffc2\053" +
    "\uffc2\056\uffc2\062\uffc2\001\002\000\026\003\uffc0\035\064" +
    "\036\075\037\067\040\073\041\072\052\uffc0\053\uffc0\056" +
    "\uffc0\062\uffc0\001\002\000\042\003\uffc5\035\uffc5\036\uffc5" +
    "\037\uffc5\040\uffc5\041\uffc5\044\uffc5\045\uffc5\046\uffc5\047" +
    "\uffc5\050\uffc5\051\uffc5\052\uffc5\053\uffc5\056\uffc5\062\uffc5" +
    "\001\002\000\026\003\uffc1\035\064\036\075\037\067\040" +
    "\073\041\072\052\uffc1\053\uffc1\056\uffc1\062\uffc1\001\002" +
    "\000\026\003\uffbe\035\064\036\075\037\067\040\073\041" +
    "\072\052\uffbe\053\uffbe\056\uffbe\062\uffbe\001\002\000\042" +
    "\003\uffc7\035\uffc7\036\uffc7\037\067\040\073\041\072\044" +
    "\uffc7\045\uffc7\046\uffc7\047\uffc7\050\uffc7\051\uffc7\052\uffc7" +
    "\053\uffc7\056\uffc7\062\uffc7\001\002\000\026\003\uffbf\035" +
    "\064\036\075\037\067\040\073\041\072\052\uffbf\053\uffbf" +
    "\056\uffbf\062\uffbf\001\002\000\042\003\uffbc\035\064\036" +
    "\075\037\067\040\073\041\072\044\071\045\066\046\070" +
    "\047\063\050\065\051\077\052\uffbc\053\uffbc\056\uffbc\062" +
    "\uffbc\001\002\000\042\003\uffba\035\uffba\036\uffba\037\uffba" +
    "\040\uffba\041\uffba\044\uffba\045\uffba\046\uffba\047\uffba\050" +
    "\uffba\051\uffba\052\uffba\053\uffba\056\uffba\062\uffba\001\002" +
    "\000\052\002\uffe2\003\uffe2\004\uffe2\005\uffe2\006\uffe2\007" +
    "\uffe2\010\uffe2\011\uffe2\012\uffe2\013\uffe2\014\uffe2\015\uffe2" +
    "\017\uffe2\020\uffe2\042\uffe2\043\uffe2\056\uffe2\057\uffe2\060" +
    "\uffe2\071\uffe2\001\002\000\036\035\064\036\075\037\067" +
    "\040\073\041\072\044\071\045\066\046\070\047\063\050" +
    "\065\051\077\052\062\053\076\056\120\001\002\000\052" +
    "\002\uffe3\003\uffe3\004\uffe3\005\uffe3\006\uffe3\007\uffe3\010" +
    "\uffe3\011\uffe3\012\uffe3\013\uffe3\014\uffe3\015\uffe3\017\uffe3" +
    "\020\uffe3\042\uffe3\043\uffe3\056\uffe3\057\uffe3\060\uffe3\071" +
    "\uffe3\001\002\000\036\035\064\036\075\037\067\040\073" +
    "\041\072\044\071\045\066\046\070\047\063\050\065\051" +
    "\077\052\062\053\076\056\122\001\002\000\052\002\uffe6" +
    "\003\uffe6\004\uffe6\005\uffe6\006\uffe6\007\uffe6\010\uffe6\011" +
    "\uffe6\012\uffe6\013\uffe6\014\uffe6\015\uffe6\017\uffe6\020\uffe6" +
    "\042\uffe6\043\uffe6\056\uffe6\057\uffe6\060\uffe6\071\uffe6\001" +
    "\002\000\036\035\064\036\075\037\067\040\073\041\072" +
    "\044\071\045\066\046\070\047\063\050\065\051\077\052" +
    "\062\053\076\056\124\001\002\000\052\002\uffe5\003\uffe5" +
    "\004\uffe5\005\uffe5\006\uffe5\007\uffe5\010\uffe5\011\uffe5\012" +
    "\uffe5\013\uffe5\014\uffe5\015\uffe5\017\uffe5\020\uffe5\042\uffe5" +
    "\043\uffe5\056\uffe5\057\uffe5\060\uffe5\071\uffe5\001\002\000" +
    "\036\035\064\036\075\037\067\040\073\041\072\044\071" +
    "\045\066\046\070\047\063\050\065\051\077\052\062\053" +
    "\076\056\126\001\002\000\052\002\uffe4\003\uffe4\004\uffe4" +
    "\005\uffe4\006\uffe4\007\uffe4\010\uffe4\011\uffe4\012\uffe4\013" +
    "\uffe4\014\uffe4\015\uffe4\017\uffe4\020\uffe4\042\uffe4\043\uffe4" +
    "\056\uffe4\057\uffe4\060\uffe4\071\uffe4\001\002\000\036\035" +
    "\064\036\075\037\067\040\073\041\072\044\071\045\066" +
    "\046\070\047\063\050\065\051\077\052\062\053\076\056" +
    "\130\001\002\000\052\002\uffe7\003\uffe7\004\uffe7\005\uffe7" +
    "\006\uffe7\007\uffe7\010\uffe7\011\uffe7\012\uffe7\013\uffe7\014" +
    "\uffe7\015\uffe7\017\uffe7\020\uffe7\042\uffe7\043\uffe7\056\uffe7" +
    "\057\uffe7\060\uffe7\071\uffe7\001\002\000\052\002\uffe0\003" +
    "\uffe0\004\uffe0\005\uffe0\006\uffe0\007\uffe0\010\uffe0\011\uffe0" +
    "\012\uffe0\013\uffe0\014\uffe0\015\uffe0\017\uffe0\020\uffe0\042" +
    "\uffe0\043\uffe0\056\uffe0\057\uffe0\060\uffe0\071\uffe0\001\002" +
    "\000\030\003\134\004\006\005\004\006\022\007\036\010" +
    "\007\011\027\012\035\013\020\056\uffd3\071\014\001\002" +
    "\000\004\056\147\001\002\000\004\062\145\001\002\000" +
    "\004\071\142\001\002\000\004\056\uffd4\001\002\000\004" +
    "\027\140\001\002\000\022\054\056\061\060\071\055\072" +
    "\050\073\057\074\053\075\051\076\052\001\002\000\040" +
    "\035\064\036\075\037\067\040\073\041\072\044\071\045" +
    "\066\046\070\047\063\050\065\051\077\052\062\053\076" +
    "\056\uffb8\062\uffb8\001\002\000\004\027\143\001\002\000" +
    "\022\054\056\061\060\071\055\072\050\073\057\074\053" +
    "\075\051\076\052\001\002\000\036\035\064\036\075\037" +
    "\067\040\073\041\072\044\071\045\066\046\070\047\063" +
    "\050\065\051\077\052\062\053\076\056\uffd5\001\002\000" +
    "\044\003\025\004\006\005\004\006\022\007\036\010\007" +
    "\011\027\012\035\013\020\014\013\017\032\020\010\042" +
    "\024\043\030\056\005\057\031\071\014\001\002\000\052" +
    "\002\uffd6\003\uffd6\004\uffd6\005\uffd6\006\uffd6\007\uffd6\010" +
    "\uffd6\011\uffd6\012\uffd6\013\uffd6\014\uffd6\015\uffd6\017\uffd6" +
    "\020\uffd6\042\uffd6\043\uffd6\056\uffd6\057\uffd6\060\uffd6\071" +
    "\uffd6\001\002\000\024\054\056\056\uffd1\061\060\071\055" +
    "\072\050\073\057\074\053\075\051\076\052\001\002\000" +
    "\004\056\152\001\002\000\036\035\064\036\075\037\067" +
    "\040\073\041\072\044\071\045\066\046\070\047\063\050" +
    "\065\051\077\052\062\053\076\056\uffd2\001\002\000\006" +
    "\062\uffcf\071\014\001\002\000\004\062\155\001\002\000" +
    "\004\062\uffd0\001\002\000\044\003\025\004\006\005\004" +
    "\006\022\007\036\010\007\011\027\012\035\013\020\014" +
    "\013\017\032\020\010\042\024\043\030\056\005\057\031" +
    "\071\014\001\002\000\052\002\uffd8\003\uffd8\004\uffd8\005" +
    "\uffd8\006\uffd8\007\uffd8\010\uffd8\011\uffd8\012\uffd8\013\uffd8" +
    "\014\uffd8\015\uffd8\017\uffd8\020\uffd8\042\uffd8\043\uffd8\056" +
    "\uffd8\057\uffd8\060\uffd8\071\uffd8\001\002\000\052\002\ufff4" +
    "\003\ufff4\004\ufff4\005\ufff4\006\ufff4\007\ufff4\010\ufff4\011" +
    "\ufff4\012\ufff4\013\ufff4\014\ufff4\015\ufff4\017\ufff4\020\ufff4" +
    "\042\ufff4\043\ufff4\056\ufff4\057\ufff4\060\ufff4\071\ufff4\001" +
    "\002\000\046\003\025\004\006\005\004\006\022\007\036" +
    "\010\007\011\027\012\035\013\020\014\013\017\032\020" +
    "\010\042\024\043\030\056\005\057\031\060\161\071\014" +
    "\001\002\000\052\002\ufff5\003\ufff5\004\ufff5\005\ufff5\006" +
    "\ufff5\007\ufff5\010\ufff5\011\ufff5\012\ufff5\013\ufff5\014\ufff5" +
    "\015\ufff5\017\ufff5\020\ufff5\042\ufff5\043\ufff5\056\ufff5\057" +
    "\ufff5\060\ufff5\071\ufff5\001\002\000\050\002\ufffe\003\ufffe" +
    "\004\ufffe\005\ufffe\006\ufffe\007\ufffe\010\ufffe\011\ufffe\012" +
    "\ufffe\013\ufffe\014\ufffe\017\ufffe\020\ufffe\042\ufffe\043\ufffe" +
    "\056\ufffe\057\ufffe\060\ufffe\071\ufffe\001\002\000\004\056" +
    "\164\001\002\000\052\002\uffde\003\uffde\004\uffde\005\uffde" +
    "\006\uffde\007\uffde\010\uffde\011\uffde\012\uffde\013\uffde\014" +
    "\uffde\015\uffde\017\uffde\020\uffde\042\uffde\043\uffde\056\uffde" +
    "\057\uffde\060\uffde\071\uffde\001\002\000\004\056\167\001" +
    "\002\000\052\002\ufff6\003\ufff6\004\ufff6\005\ufff6\006\ufff6" +
    "\007\ufff6\010\ufff6\011\ufff6\012\ufff6\013\ufff6\014\ufff6\015" +
    "\ufff6\017\ufff6\020\ufff6\042\ufff6\043\ufff6\056\ufff6\057\ufff6" +
    "\060\ufff6\071\ufff6\001\002\000\052\002\ufff0\003\ufff0\004" +
    "\ufff0\005\ufff0\006\ufff0\007\ufff0\010\ufff0\011\ufff0\012\ufff0" +
    "\013\ufff0\014\ufff0\015\ufff0\017\ufff0\020\ufff0\042\ufff0\043" +
    "\ufff0\056\ufff0\057\ufff0\060\ufff0\071\ufff0\001\002\000\004" +
    "\056\171\001\002\000\052\002\uffdf\003\uffdf\004\uffdf\005" +
    "\uffdf\006\uffdf\007\uffdf\010\uffdf\011\uffdf\012\uffdf\013\uffdf" +
    "\014\uffdf\015\uffdf\017\uffdf\020\uffdf\042\uffdf\043\uffdf\056" +
    "\uffdf\057\uffdf\060\uffdf\071\uffdf\001\002\000\004\002\001" +
    "\001\002\000\010\003\176\027\175\056\174\001\002\000" +
    "\052\002\ufff2\003\ufff2\004\ufff2\005\ufff2\006\ufff2\007\ufff2" +
    "\010\ufff2\011\ufff2\012\ufff2\013\ufff2\014\ufff2\015\ufff2\017" +
    "\ufff2\020\ufff2\042\ufff2\043\ufff2\056\ufff2\057\ufff2\060\ufff2" +
    "\071\ufff2\001\002\000\022\054\056\061\060\071\055\072" +
    "\050\073\057\074\053\075\051\076\052\001\002\000\052" +
    "\002\ufff1\003\ufff1\004\ufff1\005\ufff1\006\ufff1\007\ufff1\010" +
    "\ufff1\011\ufff1\012\ufff1\013\ufff1\014\ufff1\015\ufff1\017\ufff1" +
    "\020\ufff1\042\ufff1\043\ufff1\056\ufff1\057\ufff1\060\ufff1\071" +
    "\ufff1\001\002\000\036\035\064\036\075\037\067\040\073" +
    "\041\072\044\071\045\066\046\070\047\063\050\065\051" +
    "\077\052\062\053\076\056\200\001\002\000\052\002\ufff3" +
    "\003\ufff3\004\ufff3\005\ufff3\006\ufff3\007\ufff3\010\ufff3\011" +
    "\ufff3\012\ufff3\013\ufff3\014\ufff3\015\ufff3\017\ufff3\020\ufff3" +
    "\042\ufff3\043\ufff3\056\ufff3\057\ufff3\060\ufff3\071\ufff3\001" +
    "\002\000\022\054\056\061\060\071\055\072\050\073\057" +
    "\074\053\075\051\076\052\001\002\000\004\062\203\001" +
    "\002\000\044\003\025\004\006\005\004\006\022\007\036" +
    "\010\007\011\027\012\035\013\020\014\013\017\032\020" +
    "\010\042\024\043\030\056\005\057\031\071\014\001\002" +
    "\000\052\002\uffdb\003\uffdb\004\uffdb\005\uffdb\006\uffdb\007" +
    "\uffdb\010\uffdb\011\uffdb\012\uffdb\013\uffdb\014\uffdb\015\uffdb" +
    "\017\uffdb\020\uffdb\042\uffdb\043\uffdb\056\uffdb\057\uffdb\060" +
    "\uffdb\071\uffdb\001\002\000\040\003\206\035\064\036\075" +
    "\037\067\040\073\041\072\044\071\045\066\046\070\047" +
    "\063\050\065\051\077\052\062\053\076\062\207\001\002" +
    "\000\052\002\uffda\003\uffda\004\uffda\005\uffda\006\uffda\007" +
    "\uffda\010\uffda\011\uffda\012\uffda\013\uffda\014\uffda\015\uffda" +
    "\017\uffda\020\uffda\042\uffda\043\uffda\056\uffda\057\uffda\060" +
    "\uffda\071\uffda\001\002\000\044\003\025\004\006\005\004" +
    "\006\022\007\036\010\007\011\027\012\035\013\020\014" +
    "\013\017\032\020\010\042\024\043\030\056\005\057\031" +
    "\071\014\001\002\000\052\002\uffdd\003\uffdd\004\uffdd\005" +
    "\uffdd\006\uffdd\007\uffdd\010\uffdd\011\uffdd\012\uffdd\013\uffdd" +
    "\014\uffdd\015\uffdd\017\uffdd\020\uffdd\042\uffdd\043\uffdd\056" +
    "\uffdd\057\uffdd\060\uffdd\071\uffdd\001\002\000\044\003\025" +
    "\004\006\005\004\006\022\007\036\010\007\011\027\012" +
    "\035\013\020\014\013\017\032\020\010\042\024\043\030" +
    "\056\005\057\031\071\014\001\002\000\052\002\uffdc\003" +
    "\uffdc\004\uffdc\005\uffdc\006\uffdc\007\uffdc\010\uffdc\011\uffdc" +
    "\012\uffdc\013\uffdc\014\uffdc\015\uffdc\017\uffdc\020\uffdc\042" +
    "\uffdc\043\uffdc\056\uffdc\057\uffdc\060\uffdc\071\uffdc\001\002" +
    "\000\022\054\056\061\060\071\055\072\050\073\057\074" +
    "\053\075\051\076\052\001\002\000\040\003\215\035\064" +
    "\036\075\037\067\040\073\041\072\044\071\045\066\046" +
    "\070\047\063\050\065\051\077\052\062\053\076\062\216" +
    "\001\002\000\052\002\uffd7\003\uffd7\004\uffd7\005\uffd7\006" +
    "\uffd7\007\uffd7\010\uffd7\011\uffd7\012\uffd7\013\uffd7\014\uffd7" +
    "\015\uffd7\017\uffd7\020\uffd7\042\uffd7\043\uffd7\056\uffd7\057" +
    "\uffd7\060\uffd7\071\uffd7\001\002\000\044\003\025\004\006" +
    "\005\004\006\022\007\036\010\007\011\027\012\035\013" +
    "\020\014\013\017\032\020\010\042\024\043\030\056\005" +
    "\057\031\071\014\001\002\000\052\002\uffd9\003\uffd9\004" +
    "\uffd9\005\uffd9\006\uffd9\007\uffd9\010\uffd9\011\uffd9\012\uffd9" +
    "\013\uffd9\014\uffd9\015\uffd9\017\uffd9\020\uffd9\042\uffd9\043" +
    "\uffd9\056\uffd9\057\uffd9\060\uffd9\071\uffd9\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\215\000\026\002\015\003\033\004\014\006\010\007" +
    "\020\010\011\011\025\012\022\013\016\017\032\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\003\033\004\014" +
    "\007\161\010\011\011\025\012\022\013\016\017\032\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\017\167\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\017\162\001\001" +
    "\000\024\003\033\004\014\006\157\007\020\010\011\011" +
    "\025\012\022\013\016\017\032\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\005\126\001\001" +
    "\000\004\005\124\001\001\000\004\005\122\001\001\000" +
    "\004\005\120\001\001\000\004\005\116\001\001\000\004" +
    "\005\053\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\114\001\001\000\002\001\001\000\004\005\060\001\001" +
    "\000\002\001\001\000\004\005\113\001\001\000\004\005" +
    "\112\001\001\000\004\005\111\001\001\000\004\005\110" +
    "\001\001\000\004\005\107\001\001\000\004\005\106\001" +
    "\001\000\004\005\105\001\001\000\004\005\104\001\001" +
    "\000\004\005\103\001\001\000\004\005\102\001\001\000" +
    "\002\001\001\000\004\005\101\001\001\000\004\005\100" +
    "\001\001\000\004\005\077\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\004\134\014" +
    "\132\017\136\020\135\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\005\140\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\005\143\001\001\000\002\001\001\000" +
    "\022\003\033\004\014\007\145\010\011\011\025\012\022" +
    "\013\016\017\032\001\001\000\002\001\001\000\006\005" +
    "\150\015\147\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\016\152\017\136\020\153\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\003\033\004\014\007\155" +
    "\010\011\011\025\012\022\013\016\017\032\001\001\000" +
    "\002\001\001\000\002\001\001\000\022\003\033\004\014" +
    "\007\161\010\011\011\025\012\022\013\016\017\032\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\176\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\005\204\001\001\000\002\001\001\000" +
    "\022\003\033\004\014\007\203\010\011\011\025\012\022" +
    "\013\016\017\032\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\003\033\004\014\007\207" +
    "\010\011\011\025\012\022\013\016\017\032\001\001\000" +
    "\002\001\001\000\022\003\033\004\014\007\211\010\011" +
    "\011\025\012\022\013\016\017\032\001\001\000\002\001" +
    "\001\000\004\005\213\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\003\033\004\014\007\216\010\011\011" +
    "\025\012\022\013\016\017\032\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    protected Symbol lastErrorToken;
    public void report_fatal_error(String mensaje, Object informacion) { report_error(mensaje, informacion); }
    public void syntax_error(Symbol token_actual) {
        this.lastErrorToken = token_actual;
        String mensajeError = "Error de sintaxis. ";
        if (token_actual != null && token_actual.value != null) {
            mensajeError += "Token inesperado: '" + token_actual.value + "'.";
        }
        System.err.println(mensajeError + " En la línea: " + (token_actual.left + 1) + ", Columna: " + (token_actual.right + 1));
    }
    public void report_error(String mensaje, Object informacion) {
        if (informacion instanceof Symbol) {
            Symbol s = ((Symbol) informacion);
            if (s.left >= 0 && s.right >= 0) {
                syntax_error(s);
                System.err.println(mensaje + " Cerca de la línea: " + (s.left + 1) + ", Columna: " + (s.right + 1));
                return;
            }
        }
        System.err.println(mensaje);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintactico$actions {
  private final Sintactico parser;

  /** Constructor */
  CUP$Sintactico$actions(Sintactico parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // asignacion_expr ::= lvalue ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("asignacion_expr",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // lvalue ::= ID 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lvalue",13, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expresion ::= NOT expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expresion ::= expresion OR expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expresion ::= expresion AND expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expresion ::= expresion MENOR_IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expresion ::= expresion MAYOR_IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expresion ::= expresion MENOR expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expresion ::= expresion MAYOR expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expresion ::= expresion DIFERENCIA expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expresion ::= expresion IGUAL expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expresion ::= expresion MODULO expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresion ::= expresion DIVISION expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresion ::= expresion MULTIPLICACION expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresion ::= expresion RESTA expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresion ::= expresion SUMA expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresion ::= PARENTESIS_APERTURA expresion PARENTESIS_CIERRE 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresion ::= ID 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresion ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresion ::= CARACTER 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion ::= CADENA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresion ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion ::= ENTERO 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // for_actualizacion ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_actualizacion",12, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // for_actualizacion ::= asignacion_expr 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_actualizacion",12, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // for_condicion ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_condicion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // for_condicion ::= expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_condicion",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // for_init ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_init",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // for_init ::= asignacion_expr 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_init",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // for_init ::= tipo_dato ID ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_init",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // sentencia_iterativa ::= FOR PARENTESIS_APERTURA error PARENTESIS_CIERRE sentencia 
            {
              Object RESULT =null;
		 parser.report_error("Estructura interna del FOR inválida (inicialización; condición; actualización).", null); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_iterativa",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // sentencia_iterativa ::= WHILE PARENTESIS_APERTURA expresion error 
            {
              Object RESULT =null;
		 parser.report_error("')' faltante después de la condición del WHILE.", null); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_iterativa",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // sentencia_iterativa ::= FOR PARENTESIS_APERTURA for_init PUNTOYCOMA for_condicion PUNTOYCOMA for_actualizacion PARENTESIS_CIERRE sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_iterativa",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // sentencia_iterativa ::= WHILE PARENTESIS_APERTURA expresion PARENTESIS_CIERRE sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_iterativa",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // sentencia_condicional ::= IF PARENTESIS_APERTURA expresion error 
            {
              Object RESULT =null;
		 parser.report_error("')' faltante después de la condición del IF.", null); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_condicional",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // sentencia_condicional ::= IF error PARENTESIS_CIERRE sentencia 
            {
              Object RESULT =null;
		 parser.report_error("Expresión inválida o '(' faltante en la condición del IF.", null); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_condicional",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // sentencia_condicional ::= IF PARENTESIS_APERTURA expresion PARENTESIS_CIERRE sentencia ELSE sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_condicional",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-6)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // sentencia_condicional ::= IF PARENTESIS_APERTURA expresion PARENTESIS_CIERRE sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_condicional",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // sentencia_asignacion ::= DECREMENTO lvalue PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // sentencia_asignacion ::= INCREMENTO lvalue PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // sentencia_asignacion ::= lvalue DECREMENTO PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // sentencia_asignacion ::= lvalue INCREMENTO PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // sentencia_asignacion ::= lvalue A_MODULO expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sentencia_asignacion ::= lvalue A_DIVISION expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentencia_asignacion ::= lvalue A_MULTIPLICACION expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentencia_asignacion ::= lvalue A_RESTA expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // sentencia_asignacion ::= lvalue A_SUMA expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // sentencia_asignacion ::= lvalue ASIGNACION expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_asignacion",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo_dato ::= STRING 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo_dato ::= VOID 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipo_dato ::= BOOL 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // tipo_dato ::= CHAR 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // tipo_dato ::= DOUBLE 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // tipo_dato ::= FLOAT 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // tipo_dato ::= LONG 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // tipo_dato ::= INT 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // dec_variables ::= error ID PUNTOYCOMA 
            {
              Object RESULT =null;
		 parser.report_error("Se esperaba un tipo de dato al inicio de la declaración.", null); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_variables",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // dec_variables ::= tipo_dato ID error 
            {
              Object RESULT =null;
		 parser.report_error("Declaración mal formada. ¿Falta un ';' o una asignación válida?", null); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_variables",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // dec_variables ::= tipo_dato ID PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_variables",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // dec_variables ::= tipo_dato ID ASIGNACION expresion PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_variables",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // bloque ::= LLAVE_APERTURA LLAVE_CIERRE 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("bloque",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // bloque ::= LLAVE_APERTURA lista_sentencias LLAVE_CIERRE 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("bloque",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // sentencia ::= error PUNTOYCOMA 
            {
              Object RESULT =null;
		 parser.report_error("Error de sintaxis en la sentencia. Se recuperó en ';'.", null); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sentencia ::= PUNTOYCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sentencia ::= bloque 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentencia ::= sentencia_iterativa 
            {
              Object RESULT =null;
		 System.out.println("-> Se reconoció una sentencia iterativa."); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sentencia ::= sentencia_condicional 
            {
              Object RESULT =null;
		 System.out.println("-> Se reconoció una sentencia condicional."); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sentencia ::= sentencia_asignacion 
            {
              Object RESULT =null;
		 System.out.println("-> Se reconoció una asignación."); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sentencia ::= dec_variables 
            {
              Object RESULT =null;
		 System.out.println("-> Se reconoció una declaración."); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_sentencias",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_sentencias",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= lista_sentencias 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico$parser.done_parsing();
          return CUP$Sintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

